/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Pedidos;
import Modelo.Pedido;
import Modelo.SQLPedidos;
import com.toedter.calendar.JDateChooser;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class ModuloPedidos extends javax.swing.JPanel {

     Pedidos pds = new Pedidos();
     Pedido pedido;





    public ModuloPedidos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcmbProductos = new javax.swing.JComboBox<>();
        jtxtPrecio = new javax.swing.JTextField();
        jtxtCantidad = new javax.swing.JTextField();
        btnModificarPedido = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        jtxtIdProducto = new javax.swing.JTextField();
        jtxtIdProveedor = new javax.swing.JTextField();
        jdtFechaLlegada = new com.toedter.calendar.JDateChooser();
        btnInsertarPedido = new javax.swing.JButton();
        btnEliminarPedido = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPedidos = new javax.swing.JTable();
        jcmbPP = new javax.swing.JComboBox<>();
        jrbFTP = new javax.swing.JRadioButton();
        jrbFCP = new javax.swing.JRadioButton();
        jtxtFCP = new javax.swing.JTextField();
        jrbFRFP = new javax.swing.JRadioButton();
        jdtFPI = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jdtFPF = new com.toedter.calendar.JDateChooser();
        jrbFIdPdo = new javax.swing.JRadioButton();
        jtxtFIdPdo = new javax.swing.JTextField();
        jrbFIdPdto = new javax.swing.JRadioButton();
        jtxtFIdPdto = new javax.swing.JTextField();
        jrbFIdPvdor = new javax.swing.JRadioButton();
        jtxtFIdPvdor = new javax.swing.JTextField();
        jrbFRFLL = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jrbFP = new javax.swing.JRadioButton();
        jtxtFPP = new javax.swing.JTextField();
        jdtFPLLF = new com.toedter.calendar.JDateChooser();
        jdtFPLLI = new com.toedter.calendar.JDateChooser();
        btnFiltrar = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(72, 138, 199));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FECHA DE LLEGADA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, -1, 29));

        jcmbProductos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcmbProductos.setForeground(new java.awt.Color(153, 153, 153));
        jcmbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALIMENTOS", "DESECHABLES", "PRIMERA NECESIDAD", "SEGUNDA NECESIDAD" }));
        jcmbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbProductosActionPerformed(evt);
            }
        });
        jPanel2.add(jcmbProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jtxtPrecio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtPrecio.setForeground(new java.awt.Color(153, 153, 153));
        jtxtPrecio.setText("          PRECIO");
        jtxtPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtPrecioMouseClicked(evt);
            }
        });
        jtxtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPrecioActionPerformed(evt);
            }
        });
        jtxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtPrecioKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 100, 30));

        jtxtCantidad.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtCantidad.setForeground(new java.awt.Color(153, 153, 153));
        jtxtCantidad.setText("      CANTIDAD");
        jtxtCantidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCantidadMouseClicked(evt);
            }
        });
        jtxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCantidadActionPerformed(evt);
            }
        });
        jtxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtCantidadKeyTyped(evt);
            }
        });
        jPanel2.add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, 30));

        btnModificarPedido.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnModificarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPedido.setText("MODIFICAR");
        btnModificarPedido.setBorder(null);
        btnModificarPedido.setBorderPainted(false);
        btnModificarPedido.setContentAreaFilled(false);
        btnModificarPedido.setEnabled(false);
        btnModificarPedido.setFocusPainted(false);
        btnModificarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarPedidoMouseClicked(evt);
            }
        });
        btnModificarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 100, 40));

        btnCancelarPedido.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnCancelarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarPedido.setText("CANCELAR");
        btnCancelarPedido.setBorder(null);
        btnCancelarPedido.setBorderPainted(false);
        btnCancelarPedido.setContentAreaFilled(false);
        btnCancelarPedido.setFocusPainted(false);
        btnCancelarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarPedidoMouseClicked(evt);
            }
        });
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 100, 40));

        jtxtIdProducto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtIdProducto.setForeground(new java.awt.Color(102, 102, 102));
        jtxtIdProducto.setText("CLAVE PRODUCTO");
        jtxtIdProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIdProductoMouseClicked(evt);
            }
        });
        jtxtIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdProductoActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 110, 20));

        jtxtIdProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtIdProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtIdProveedor.setText("CLAVE PROVEEDOR");
        jtxtIdProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtIdProveedorMouseClicked(evt);
            }
        });
        jtxtIdProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtIdProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 110, 20));

        jdtFechaLlegada.setDateFormatString("yyyy-MM-dd");
        jdtFechaLlegada.setMaxSelectableDate(new java.util.Date(2556169310000L));
        jdtFechaLlegada.setMinSelectableDate(new java.util.Date(1622527310000L));
        jdtFechaLlegada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jdtFechaLlegadaMouseClicked(evt);
            }
        });
        jPanel2.add(jdtFechaLlegada, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, -1));

        btnInsertarPedido.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnInsertarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertarPedido.setText("INSERTAR");
        btnInsertarPedido.setBorder(null);
        btnInsertarPedido.setBorderPainted(false);
        btnInsertarPedido.setContentAreaFilled(false);
        btnInsertarPedido.setFocusPainted(false);
        btnInsertarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarPedidoMouseClicked(evt);
            }
        });
        jPanel2.add(btnInsertarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 100, 40));

        btnEliminarPedido.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnEliminarPedido.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPedido.setText("ELIMINAR");
        btnEliminarPedido.setBorder(null);
        btnEliminarPedido.setBorderPainted(false);
        btnEliminarPedido.setContentAreaFilled(false);
        btnEliminarPedido.setEnabled(false);
        btnEliminarPedido.setFocusPainted(false);
        btnEliminarPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPedidoMouseClicked(evt);
            }
        });
        btnEliminarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPedidoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 470, 100, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 290, 590));

        jPanel3.setBackground(new java.awt.Color(63, 50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 590));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtblPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID PEDIDO", "CLAVE PRODUCTO", "CLAVE PROVEEDOR", "CATEGORIA", "CANTIDAD", "FECHA PETICION", "FECHA LLEGADA", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblPedidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblPedidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPedidos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 40, 769, -1));

        jcmbPP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALIMENTOS", "DESECHABLES", "PRIMERA NECESIDAD", "SEGUNDA NECESIDAD" }));
        add(jcmbPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(1116, 7, 150, -1));

        buttonGroup1.add(jrbFTP);
        jrbFTP.setText("Filtrar todos los registros");
        jrbFTP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFTPMouseClicked(evt);
            }
        });
        add(jrbFTP, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 6, -1, -1));

        buttonGroup1.add(jrbFCP);
        jrbFCP.setText("Filtrar una cantidad");
        jrbFCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFCPMouseClicked(evt);
            }
        });
        add(jrbFCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(697, 6, -1, -1));

        jtxtFCP.setEnabled(false);
        add(jtxtFCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 8, 91, -1));

        buttonGroup1.add(jrbFRFP);
        jrbFRFP.setText("Filtrar por rango de fecha de petición");
        jrbFRFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFRFPMouseClicked(evt);
            }
        });
        add(jrbFRFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 467, -1, -1));

        jdtFPI.setDateFormatString("yyyy-MM-dd");
        jdtFPI.setEnabled(false);
        jdtFPI.setMaxSelectableDate(new java.util.Date(2524629600000L));
        jdtFPI.setMinSelectableDate(new java.util.Date(1622869200000L));
        add(jdtFPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 467, -1, -1));

        jLabel2.setText("A");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 467, 18, 29));

        jdtFPF.setDateFormatString("yyyy-MM-dd");
        jdtFPF.setEnabled(false);
        jdtFPF.setMaxSelectableDate(new java.util.Date(2524629600000L));
        jdtFPF.setMinSelectableDate(new java.util.Date(1622869200000L));
        add(jdtFPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(915, 467, -1, -1));

        buttonGroup1.add(jrbFIdPdo);
        jrbFIdPdo.setText("Filtrar por id Pedido");
        jrbFIdPdo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFIdPdoMouseClicked(evt);
            }
        });
        add(jrbFIdPdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1046, 467, -1, -1));

        jtxtFIdPdo.setEnabled(false);
        add(jtxtFIdPdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1218, 469, 59, -1));

        buttonGroup1.add(jrbFIdPdto);
        jrbFIdPdto.setText("Filtrar por id Producto");
        jrbFIdPdto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFIdPdtoMouseClicked(evt);
            }
        });
        add(jrbFIdPdto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1049, 502, -1, -1));

        jtxtFIdPdto.setEnabled(false);
        add(jtxtFIdPdto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1218, 504, 59, -1));

        buttonGroup1.add(jrbFIdPvdor);
        jrbFIdPvdor.setText("Filtrar por id Proveedor");
        jrbFIdPvdor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFIdPvdorMouseClicked(evt);
            }
        });
        add(jrbFIdPvdor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1046, 531, -1, -1));

        jtxtFIdPvdor.setEnabled(false);
        add(jtxtFIdPvdor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1218, 533, 59, -1));

        buttonGroup1.add(jrbFRFLL);
        jrbFRFLL.setText("Filtrar por rango de fecha de llegada");
        jrbFRFLL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFRFLLMouseClicked(evt);
            }
        });
        add(jrbFRFLL, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 502, -1, -1));

        jLabel3.setText("A");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 502, 18, 29));

        buttonGroup1.add(jrbFP);
        jrbFP.setText("Filtrar por precio");
        jrbFP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFPMouseClicked(evt);
            }
        });
        add(jrbFP, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 531, -1, -1));

        jtxtFPP.setEnabled(false);
        add(jtxtFPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 533, 59, -1));

        jdtFPLLF.setDateFormatString("yyyy-MM-dd");
        jdtFPLLF.setEnabled(false);
        jdtFPLLF.setMaxSelectableDate(new java.util.Date(2524629600000L));
        jdtFPLLF.setMinSelectableDate(new java.util.Date(1622869200000L));
        add(jdtFPLLF, new org.netbeans.lib.awtextra.AbsoluteConstraints(917, 502, -1, -1));

        jdtFPLLI.setDateFormatString("yyyy-MM-dd");
        jdtFPLLI.setEnabled(false);
        jdtFPLLI.setMaxSelectableDate(new java.util.Date(2524629600000L));
        jdtFPLLI.setMinSelectableDate(new java.util.Date(1622869200000L));
        add(jdtFPLLI, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 502, -1, -1));

        btnFiltrar.setBackground(new java.awt.Color(0, 0, 0));
        btnFiltrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltrar.setText("Filtrar");
        btnFiltrar.setEnabled(false);
        btnFiltrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarMouseClicked(evt);
            }
        });
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, 205, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jcmbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbProductosActionPerformed

    private void jtxtPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtPrecioMouseClicked
        jtxtPrecio.setText("");
        if(jtxtPrecio.getText().equals("")){
            jtxtPrecio.setText("");
        }
        if(jtxtCantidad.getText().equals("")){

            jtxtCantidad.setText("    CANTIDAD");

        }
        if(jtxtIdProducto.getText().equals("")){

            jtxtIdProducto.setText(" CLAVE PRODUCTO");

        }
        if(jtxtIdProveedor.getText().equals("")){

            jtxtIdProveedor.setText(" CLAVE PROVEEDOR");

        }
    }//GEN-LAST:event_jtxtPrecioMouseClicked

    private void jtxtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPrecioActionPerformed

    private void jtxtCantidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCantidadMouseClicked
        jtxtCantidad.setText("");
        if(jtxtCantidad.getText().equals("")){
            jtxtCantidad.setText("");
        }
        if(jtxtPrecio.getText().equals("")){

            jtxtPrecio.setText("  PRECIO");

        }
        if(jtxtIdProducto.getText().equals("")){

            jtxtIdProducto.setText(" CLAVE PRODUCTO");

        }
        if(jtxtIdProveedor.getText().equals("")){

            jtxtIdProveedor.setText(" CLAVE PROVEEDOR");

        }
    }//GEN-LAST:event_jtxtCantidadMouseClicked

    private void jtxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCantidadActionPerformed

    private void btnModificarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarPedidoMouseClicked

       this.pds.modificarRegistroPedido(this);

    }//GEN-LAST:event_btnModificarPedidoMouseClicked

    private void btnModificarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarPedidoActionPerformed

    private void btnCancelarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarPedidoMouseClicked

        this.pds.cancelarEdicionPedidos(this);
        
    }//GEN-LAST:event_btnCancelarPedidoMouseClicked

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void jtxtIdProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIdProductoMouseClicked
        jtxtIdProducto.setText("");
        if(jtxtIdProducto.getText().equals("")){
            jtxtIdProducto.setText("");
        }
        if(jtxtPrecio.getText().equals("")){

            jtxtPrecio.setText("  PRECIO");

        }
        if(jtxtCantidad.getText().equals("")){

            jtxtCantidad.setText(" CANTIDAD");

        }
        if(jtxtIdProveedor.getText().equals("")){

            jtxtIdProveedor.setText(" CLAVE PROVEEDOR");

        }
    }//GEN-LAST:event_jtxtIdProductoMouseClicked

    private void jtxtIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdProductoActionPerformed

    private void jtxtIdProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtIdProveedorMouseClicked
        jtxtIdProveedor.setText("");
        if(jtxtIdProveedor.getText().equals("")){
            jtxtIdProveedor.setText("");
        }
        if(jtxtPrecio.getText().equals("")){

            jtxtPrecio.setText(" PRECIO");

        }
        if(jtxtIdProducto.getText().equals("")){

            jtxtIdProducto.setText(" CLAVE PRODUCTO");

        }
        if(jtxtIdProveedor.getText().equals("")){

            jtxtCantidad.setText(" CANTIDAD");

        }
    }//GEN-LAST:event_jtxtIdProveedorMouseClicked

    private void jtxtIdProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdProveedorActionPerformed

    private void btnInsertarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarPedidoMouseClicked

        boolean estadoCampos;    
        this.pedido = new Pedido();
    
        estadoCampos = this.pds.obtenerinformación(this);
        
        if(estadoCampos == false)
        {
            
          JOptionPane.showMessageDialog(null, "Inserta Información verídica");
            
        }else
        {
        
        
          this.pds.agregarRegistroPedido(this);
        
        }
    }//GEN-LAST:event_btnInsertarPedidoMouseClicked

    private void btnEliminarPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPedidoMouseClicked

        this.pds.EliminarRegistroUsuario(this);

    }//GEN-LAST:event_btnEliminarPedidoMouseClicked

    private void btnEliminarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPedidoActionPerformed

    private void jtblPedidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPedidosMouseClicked

        this.pds.verificarCamposSeleccionados(this);

    }//GEN-LAST:event_jtblPedidosMouseClicked

    private void jtxtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPrecioKeyReleased
    }//GEN-LAST:event_jtxtPrecioKeyReleased

    private void jtxtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyReleased

        this.pds.establecerPrecioPedido(this);
        
    }//GEN-LAST:event_jtxtCantidadKeyReleased

    private void jtxtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyPressed

    }//GEN-LAST:event_jtxtCantidadKeyPressed

    private void jdtFechaLlegadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jdtFechaLlegadaMouseClicked

        
        
    }//GEN-LAST:event_jdtFechaLlegadaMouseClicked

    private void jtxtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtCantidadKeyTyped

    }//GEN-LAST:event_jtxtCantidadKeyTyped

    private void btnFiltrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarMouseClicked

        this.pds.Consultar(this);
        
    }//GEN-LAST:event_btnFiltrarMouseClicked

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void jrbFTPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFTPMouseClicked

        pedido = new Pedido();
        this.btnFiltrar.setEnabled(true);
        this.jdtFPF.setEnabled(false);
        this.jdtFPF.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jdtFPLLI.setEnabled(false);
        this.jdtFPLLI.setDate(null);
        this.jdtFPLLF.setEnabled(false);
        this.jdtFPLLF.setDate(null);
        this.jtxtFIdPdo.setEnabled(false);
        this.jtxtFIdPdo.setText("");
        this.jtxtFIdPdto.setEnabled(false);
        this.jtxtFIdPdto.setText("");
        this.jtxtFIdPvdor.setEnabled(false);
        this.jtxtFIdPvdor.setText("");
        this.jtxtFCP.setEnabled(false);
        this.jtxtFCP.setText("");
        this.jtxtFPP.setEnabled(false);
        this.jtxtFPP.setText("");

    }//GEN-LAST:event_jrbFTPMouseClicked

    private void jrbFCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFCPMouseClicked

        pedido = new Pedido();
        this.btnFiltrar.setEnabled(true);
        this.jtxtFCP.setEnabled(true);
        this.jdtFPF.setEnabled(false);
        this.jdtFPF.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jdtFPLLI.setEnabled(false);
        this.jdtFPLLI.setDate(null);
        this.jdtFPLLF.setEnabled(false);
        this.jdtFPLLF.setDate(null);
        this.jtxtFIdPdo.setEnabled(false);
        this.jtxtFIdPdo.setText("");
        this.jtxtFIdPdto.setEnabled(false);
        this.jtxtFIdPdto.setText("");
        this.jtxtFIdPvdor.setEnabled(false);
        this.jtxtFIdPvdor.setText("");
        this.jtxtFPP.setEnabled(false);
        this.jtxtFPP.setText("");
        
    }//GEN-LAST:event_jrbFCPMouseClicked

    private void jrbFRFPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFRFPMouseClicked

        pedido = new Pedido();
        this.btnFiltrar.setEnabled(true);
        this.jdtFPI.setEnabled(true);
        this.jdtFPF.setEnabled(true);
        this.jdtFPLLI.setEnabled(false);
        this.jdtFPLLI.setDate(null);
        this.jdtFPLLF.setEnabled(false);
        this.jdtFPLLF.setDate(null);
        this.jtxtFIdPdo.setEnabled(false);
        this.jtxtFIdPdo.setText("");
        this.jtxtFIdPdto.setEnabled(false);
        this.jtxtFIdPdto.setText("");
        this.jtxtFIdPvdor.setEnabled(false);
        this.jtxtFIdPvdor.setText("");
        this.jtxtFCP.setEnabled(false);
        this.jtxtFCP.setText("");
        this.jtxtFPP.setEnabled(false);
        this.jtxtFPP.setText("");
        
    }//GEN-LAST:event_jrbFRFPMouseClicked

    private void jrbFRFLLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFRFLLMouseClicked

        pedido = new Pedido();
        
        this.btnFiltrar.setEnabled(true);
        this.jdtFPLLI.setEnabled(true);
        this.jdtFPLLF.setEnabled(true);
        this.jdtFPF.setEnabled(false);
        this.jdtFPF.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jtxtFIdPdo.setEnabled(false);
        this.jtxtFIdPdo.setText("");
        this.jtxtFIdPdto.setEnabled(false);
        this.jtxtFIdPdto.setText("");
        this.jtxtFIdPvdor.setEnabled(false);
        this.jtxtFIdPvdor.setText("");
        this.jtxtFCP.setEnabled(false);
        this.jtxtFCP.setText("");
        this.jtxtFPP.setEnabled(false);
        this.jtxtFPP.setText("");

    }//GEN-LAST:event_jrbFRFLLMouseClicked

    private void jrbFPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFPMouseClicked

        pedido = new Pedido();
        this.btnFiltrar.setEnabled(true);
        this.jtxtFPP.setEnabled(true);
        this.jdtFPF.setEnabled(false);
        this.jdtFPF.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jdtFPLLI.setEnabled(false);
        this.jdtFPLLI.setDate(null);
        this.jdtFPLLF.setEnabled(false);
        this.jdtFPLLF.setDate(null);
        this.jtxtFIdPdo.setEnabled(false);
        this.jtxtFIdPdo.setText("");
        this.jtxtFIdPdto.setEnabled(false);
        this.jtxtFIdPdto.setText("");
        this.jtxtFIdPvdor.setEnabled(false);
        this.jtxtFIdPvdor.setText("");
        this.jtxtFCP.setEnabled(false);
        this.jtxtFCP.setText("");
        

    }//GEN-LAST:event_jrbFPMouseClicked

    private void jrbFIdPdoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFIdPdoMouseClicked

        pedido = new Pedido();
        this.btnFiltrar.setEnabled(true);
        this.jtxtFIdPdo.setEnabled(true);
        this.jdtFPF.setEnabled(false);
        this.jdtFPF.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jdtFPLLF.setEnabled(false);
        this.jdtFPLLF.setDate(null);
        this.jdtFPLLI.setEnabled(false);
        this.jdtFPLLI.setDate(null);
        this.jtxtFIdPdto.setEnabled(false);
        this.jtxtFIdPdto.setText("");
        this.jtxtFIdPvdor.setEnabled(false);
        this.jtxtFIdPvdor.setText("");
        this.jtxtFCP.setEnabled(false);
        this.jtxtFCP.setText("");
        this.jtxtFPP.setEnabled(false);
        this.jtxtFPP.setText("");


    }//GEN-LAST:event_jrbFIdPdoMouseClicked

    private void jrbFIdPdtoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFIdPdtoMouseClicked

        pedido = new Pedido();
        this.btnFiltrar.setEnabled(true);
        this.jtxtFIdPdto.setEnabled(true);
        this.jdtFPF.setEnabled(false);
        this.jdtFPF.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jdtFPLLF.setEnabled(false);
        this.jdtFPLLF.setDate(null);
        this.jdtFPLLI.setEnabled(false);
        this.jdtFPLLI.setDate(null);
        this.jtxtFIdPdo.setEnabled(false);
        this.jtxtFIdPdo.setText("");
        this.jtxtFIdPvdor.setEnabled(false);
        this.jtxtFIdPvdor.setText("");
        this.jtxtFCP.setEnabled(false);
        this.jtxtFCP.setText("");
        this.jtxtFPP.setEnabled(false);
        this.jtxtFPP.setText("");

        
    }//GEN-LAST:event_jrbFIdPdtoMouseClicked

    private void jrbFIdPvdorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFIdPvdorMouseClicked

        pedido = new Pedido();
        this.btnFiltrar.setEnabled(true);
        this.jtxtFIdPvdor.setEnabled(true);
        this.jdtFPF.setEnabled(false);
        this.jdtFPF.setDate(null);
        this.jdtFPI.setEnabled(false);
        this.jdtFPI.setDate(null);
        this.jdtFPLLF.setEnabled(false);
        this.jdtFPLLF.setDate(null);
        this.jdtFPLLI.setEnabled(false);
        this.jdtFPLLI.setDate(null);
        this.jtxtFIdPdo.setEnabled(false);
        this.jtxtFIdPdo.setText("");
        this.jtxtFIdPdto.setEnabled(false);
        this.jtxtFIdPdto.setText("");
        this.jtxtFCP.setEnabled(false);
        this.jtxtFCP.setText("");
        this.jtxtFPP.setEnabled(false);
        this.jtxtFPP.setText("");

        
    }//GEN-LAST:event_jrbFIdPvdorMouseClicked

    public JButton getBtnCancelarPedido() {
        return btnCancelarPedido;
    }

    public void setBtnCancelarPedido(JButton btnCancelarPedido) {
        this.btnCancelarPedido = btnCancelarPedido;
    }

    public JButton getBtnEliminarPedido() {
        return btnEliminarPedido;
    }

    public void setBtnEliminarPedido(JButton btnEliminarPedido) {
        this.btnEliminarPedido = btnEliminarPedido;
    }

    public JButton getBtnInsertarPedido() {
        return btnInsertarPedido;
    }

    public void setBtnInsertarPedido(JButton btnInsertarPedido) {
        this.btnInsertarPedido = btnInsertarPedido;
    }

    public JButton getBtnModificarPedido() {
        return btnModificarPedido;
    }

    public void setBtnModificarPedido(JButton btnModificarPedido) {
        this.btnModificarPedido = btnModificarPedido;
    }

    public JComboBox<String> getJcmbProductos() {
        return jcmbProductos;
    }

    public void setJcmbProductos(JComboBox<String> jcmbProductos) {
        this.jcmbProductos = jcmbProductos;
    }
    
    public JDateChooser getJdtFechaLlegada() {
        return jdtFechaLlegada;
    }

    public void setJdtFechaLlegada(JDateChooser jdtFechaLlegada) {
        this.jdtFechaLlegada = jdtFechaLlegada;
    }

    public JTable getJtblPedidos() {
        return jtblPedidos;
    }

    public void setJtblPedidos(JTable jtblPedidos) {
        this.jtblPedidos = jtblPedidos;
    }

    public JTextField getJtxtCantidad() {
        return jtxtCantidad;
    }

    public void setJtxtCantidad(JTextField jtxtCantidad) {
        this.jtxtCantidad = jtxtCantidad;
    }

    public JTextField getJtxtIdProducto() {
        return jtxtIdProducto;
    }

    public void setJtxtIdProducto(JTextField jtxtIdProducto) {
        this.jtxtIdProducto = jtxtIdProducto;
    }

    public JTextField getJtxtIdProveedor() {
        return jtxtIdProveedor;
    }

    public void setJtxtIdProveedor(JTextField jtxtIdProveedor) {
        this.jtxtIdProveedor = jtxtIdProveedor;
    }

    public JTextField getJtxtPrecio() {
        return jtxtPrecio;
    }

    public void setJtxtPrecio(JTextField jtxtPrecio) {
        this.jtxtPrecio = jtxtPrecio;
    }

    public Pedido getPedido() {
        return pedido;
    }

    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }

    public JButton getBtnFiltrar() {
        return btnFiltrar;
    }

    public void setBtnFiltrar(JButton btnFiltrar) {
        this.btnFiltrar = btnFiltrar;
    }

    public JComboBox<String> getJcmbPP() {
        return jcmbPP;
    }

    public void setJcmbPP(JComboBox<String> jcmbPP) {
        this.jcmbPP = jcmbPP;
    }

    public JDateChooser getJdtFPF() {
        return jdtFPF;
    }

    public void setJdtFPF(JDateChooser jdtFPF) {
        this.jdtFPF = jdtFPF;
    }

    public JDateChooser getJdtFPI() {
        return jdtFPI;
    }

    public void setJdtFPI(JDateChooser jdtFPI) {
        this.jdtFPI = jdtFPI;
    }

    public JDateChooser getJdtFPLLF() {
        return jdtFPLLF;
    }

    public void setJdtFPLLF(JDateChooser jdtFPLLF) {
        this.jdtFPLLF = jdtFPLLF;
    }

    public JDateChooser getJdtFPLLI() {
        return jdtFPLLI;
    }

    public void setJdtFPLLI(JDateChooser jdtFPLLI) {
        this.jdtFPLLI = jdtFPLLI;
    }

    public JRadioButton getJrbFCP() {
        return jrbFCP;
    }

    public void setJrbFCP(JRadioButton jrbFCP) {
        this.jrbFCP = jrbFCP;
    }

    public JRadioButton getJrbFIdPdo() {
        return jrbFIdPdo;
    }

    public void setJrbFIdPdo(JRadioButton jrbFIdPdo) {
        this.jrbFIdPdo = jrbFIdPdo;
    }

    public JRadioButton getJrbFIdPdto() {
        return jrbFIdPdto;
    }

    public void setJrbFIdPdto(JRadioButton jrbFIdPdto) {
        this.jrbFIdPdto = jrbFIdPdto;
    }

    public JRadioButton getJrbFIdPvdor() {
        return jrbFIdPvdor;
    }

    public void setJrbFIdPvdor(JRadioButton jrbFIdPvdor) {
        this.jrbFIdPvdor = jrbFIdPvdor;
    }

    public JRadioButton getJrbFP() {
        return jrbFP;
    }

    public void setJrbFP(JRadioButton jrbFP) {
        this.jrbFP = jrbFP;
    }

    public JRadioButton getJrbFRFLL() {
        return jrbFRFLL;
    }

    public void setJrbFRFLL(JRadioButton jrbFRFLL) {
        this.jrbFRFLL = jrbFRFLL;
    }

    public JRadioButton getJrbFRFP() {
        return jrbFRFP;
    }

    public void setJrbFRFP(JRadioButton jrbFRFP) {
        this.jrbFRFP = jrbFRFP;
    }

    public JRadioButton getJrbFTP() {
        return jrbFTP;
    }

    public void setJrbFTP(JRadioButton jrbFTP) {
        this.jrbFTP = jrbFTP;
    }

    public JTextField getJtxtFCP() {
        return jtxtFCP;
    }

    public void setJtxtFCP(JTextField jtxtFCP) {
        this.jtxtFCP = jtxtFCP;
    }

    public JTextField getJtxtFIdPdo() {
        return jtxtFIdPdo;
    }

    public void setJtxtFIdPdo(JTextField jtxtFIdPdo) {
        this.jtxtFIdPdo = jtxtFIdPdo;
    }

    public JTextField getJtxtFIdPdto() {
        return jtxtFIdPdto;
    }

    public void setJtxtFIdPdto(JTextField jtxtFIdPdto) {
        this.jtxtFIdPdto = jtxtFIdPdto;
    }

    public JTextField getJtxtFIdPvdor() {
        return jtxtFIdPvdor;
    }

    public void setJtxtFIdPvdor(JTextField jtxtFIdPvdor) {
        this.jtxtFIdPvdor = jtxtFIdPvdor;
    }

    public JTextField getJtxtFPP() {
        return jtxtFPP;
    }

    public void setJtxtFPP(JTextField jtxtFPP) {
        this.jtxtFPP = jtxtFPP;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnEliminarPedido;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnInsertarPedido;
    private javax.swing.JButton btnModificarPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcmbPP;
    private javax.swing.JComboBox<String> jcmbProductos;
    private com.toedter.calendar.JDateChooser jdtFPF;
    private com.toedter.calendar.JDateChooser jdtFPI;
    private com.toedter.calendar.JDateChooser jdtFPLLF;
    private com.toedter.calendar.JDateChooser jdtFPLLI;
    private com.toedter.calendar.JDateChooser jdtFechaLlegada;
    private javax.swing.JRadioButton jrbFCP;
    private javax.swing.JRadioButton jrbFIdPdo;
    private javax.swing.JRadioButton jrbFIdPdto;
    private javax.swing.JRadioButton jrbFIdPvdor;
    private javax.swing.JRadioButton jrbFP;
    private javax.swing.JRadioButton jrbFRFLL;
    private javax.swing.JRadioButton jrbFRFP;
    private javax.swing.JRadioButton jrbFTP;
    private javax.swing.JTable jtblPedidos;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtFCP;
    private javax.swing.JTextField jtxtFIdPdo;
    private javax.swing.JTextField jtxtFIdPdto;
    private javax.swing.JTextField jtxtFIdPvdor;
    private javax.swing.JTextField jtxtFPP;
    private javax.swing.JTextField jtxtIdProducto;
    private javax.swing.JTextField jtxtIdProveedor;
    private javax.swing.JTextField jtxtPrecio;
    // End of variables declaration//GEN-END:variables
}
