/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Proveedores;
import Modelo.Proveedor;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author marco
 */
public class ModuloProveedores extends javax.swing.JPanel {

    /**
     * Creates new form ModuloProveedores
     */
    public ModuloProveedores() {
        initComponents();
    }

    Proveedores ps = new Proveedores();
    Proveedor proveedor;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtxtMunicipioProveedor = new javax.swing.JTextField();
        jtxtNombreProveedor = new javax.swing.JTextField();
        jtxtCodigoPostalProveedor = new javax.swing.JTextField();
        jtxtNumeroDeContacto = new javax.swing.JTextField();
        jcmbSituacionProveedor = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnInsertarProveedor = new javax.swing.JButton();
        btnModiificarProveedor = new javax.swing.JButton();
        jtxtColoniaProveedor = new javax.swing.JTextField();
        jtxtCalleProveedor = new javax.swing.JTextField();
        jtxtNumeroCalle = new javax.swing.JTextField();
        jtxtEstadoProveedor = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblProveedores = new javax.swing.JTable();
        jrbFiltrarTodosLosProveedores = new javax.swing.JRadioButton();
        jrbFiltrarAlgunosProveedores = new javax.swing.JRadioButton();
        jtxtFiltrarAlgunosProveedoresInicial = new javax.swing.JTextField();
        jtxtFiltrarAlgunosProveedoresFinal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jrbFiltrarPorIdProveedor = new javax.swing.JRadioButton();
        jrbFiltrarPorDireccion = new javax.swing.JRadioButton();
        jrbFiltrarPorSituacion = new javax.swing.JRadioButton();
        jtxtFiltrarPorIdProveedor = new javax.swing.JTextField();
        jtxtFiltroColoniaProveedor = new javax.swing.JTextField();
        jcmbFiltrarPorSituacion = new javax.swing.JComboBox<>();
        jtxtFiltroCodigoPostalProveedor = new javax.swing.JTextField();
        jrbFiltrarPorNombreProveedor = new javax.swing.JRadioButton();
        jtxtFiltrarPorNombreProveedor = new javax.swing.JTextField();
        jtxtFiltroMunicipioProveedor = new javax.swing.JTextField();
        jtxtFiltroEstadoProveedor = new javax.swing.JTextField();
        jtxtFiltroCalleProveedor = new javax.swing.JTextField();
        jtxtFiltroNumeroCasaProveedor = new javax.swing.JTextField();
        btnFiltrarProveedor = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(185, 217, 195));
        jPanel2.setForeground(new java.awt.Color(185, 217, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtMunicipioProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtMunicipioProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtMunicipioProveedor.setText("           MUNICIPIO");
        jtxtMunicipioProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtMunicipioProveedorMouseClicked(evt);
            }
        });
        jtxtMunicipioProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMunicipioProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtMunicipioProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 140, 30));

        jtxtNombreProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtNombreProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNombreProveedor.setText("                         NOMBRE");
        jtxtNombreProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNombreProveedorMouseClicked(evt);
            }
        });
        jtxtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 30));

        jtxtCodigoPostalProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtCodigoPostalProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtCodigoPostalProveedor.setText("           C.P");
        jtxtCodigoPostalProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCodigoPostalProveedorMouseClicked(evt);
            }
        });
        jtxtCodigoPostalProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCodigoPostalProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCodigoPostalProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 90, 30));

        jtxtNumeroDeContacto.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtNumeroDeContacto.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNumeroDeContacto.setText("              NUMERO DE CONTACTO");
        jtxtNumeroDeContacto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNumeroDeContactoMouseClicked(evt);
            }
        });
        jPanel2.add(jtxtNumeroDeContacto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, 30));

        jcmbSituacionProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcmbSituacionProveedor.setForeground(new java.awt.Color(153, 153, 153));
        jcmbSituacionProveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO", " " }));
        jPanel2.add(jcmbSituacionProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 80, -1));

        btnCancelar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(51, 51, 51));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 100, 40));

        btnInsertarProveedor.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnInsertarProveedor.setForeground(new java.awt.Color(51, 51, 51));
        btnInsertarProveedor.setText("INSERTAR");
        btnInsertarProveedor.setBorder(null);
        btnInsertarProveedor.setBorderPainted(false);
        btnInsertarProveedor.setContentAreaFilled(false);
        btnInsertarProveedor.setFocusPainted(false);
        btnInsertarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarProveedorMouseClicked(evt);
            }
        });
        jPanel2.add(btnInsertarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 100, 40));

        btnModiificarProveedor.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnModiificarProveedor.setForeground(new java.awt.Color(51, 51, 51));
        btnModiificarProveedor.setText("MODIFICAR");
        btnModiificarProveedor.setBorder(null);
        btnModiificarProveedor.setBorderPainted(false);
        btnModiificarProveedor.setContentAreaFilled(false);
        btnModiificarProveedor.setFocusPainted(false);
        btnModiificarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModiificarProveedorMouseClicked(evt);
            }
        });
        btnModiificarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiificarProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(btnModiificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 100, 40));

        jtxtColoniaProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtColoniaProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtColoniaProveedor.setText("              COLONIA");
        jtxtColoniaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtColoniaProveedorMouseClicked(evt);
            }
        });
        jtxtColoniaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtColoniaProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtColoniaProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 140, 30));

        jtxtCalleProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtCalleProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtCalleProveedor.setText("                CALLE");
        jtxtCalleProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtCalleProveedorMouseClicked(evt);
            }
        });
        jtxtCalleProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCalleProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtCalleProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 140, 30));

        jtxtNumeroCalle.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtNumeroCalle.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNumeroCalle.setText("        NUMERO");
        jtxtNumeroCalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNumeroCalleMouseClicked(evt);
            }
        });
        jtxtNumeroCalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumeroCalleActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtNumeroCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 90, 30));

        jtxtEstadoProveedor.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtEstadoProveedor.setForeground(new java.awt.Color(102, 102, 102));
        jtxtEstadoProveedor.setText("           ESTADO");
        jtxtEstadoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtEstadoProveedorMouseClicked(evt);
            }
        });
        jtxtEstadoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEstadoProveedorActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtEstadoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 140, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 280, 590));

        jPanel3.setBackground(new java.awt.Color(63, 50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 590));

        jtblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ", "NOMBRE ", "CALLE", "NUMERO", "COLONIA", "C.P", "MUNICIPIO", "ESTADO", "SITUACION", "CONTACTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProveedoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblProveedores);

        buttonGroup1.add(jrbFiltrarTodosLosProveedores);
        jrbFiltrarTodosLosProveedores.setText("Traer a todos los proveedores");
        jrbFiltrarTodosLosProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFiltrarTodosLosProveedoresMouseClicked(evt);
            }
        });

        buttonGroup1.add(jrbFiltrarAlgunosProveedores);
        jrbFiltrarAlgunosProveedores.setText("Traer algunos");
        jrbFiltrarAlgunosProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFiltrarAlgunosProveedoresMouseClicked(evt);
            }
        });

        jtxtFiltrarAlgunosProveedoresInicial.setEnabled(false);
        jtxtFiltrarAlgunosProveedoresInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiltrarAlgunosProveedoresInicialActionPerformed(evt);
            }
        });

        jtxtFiltrarAlgunosProveedoresFinal.setEnabled(false);

        jLabel1.setText("A");

        buttonGroup1.add(jrbFiltrarPorIdProveedor);
        jrbFiltrarPorIdProveedor.setText("Traer por ID");
        jrbFiltrarPorIdProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFiltrarPorIdProveedorMouseClicked(evt);
            }
        });

        buttonGroup1.add(jrbFiltrarPorDireccion);
        jrbFiltrarPorDireccion.setText("Traer por dirección");
        jrbFiltrarPorDireccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFiltrarPorDireccionMouseClicked(evt);
            }
        });

        buttonGroup1.add(jrbFiltrarPorSituacion);
        jrbFiltrarPorSituacion.setText("Traer por situación");
        jrbFiltrarPorSituacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFiltrarPorSituacionMouseClicked(evt);
            }
        });

        jtxtFiltrarPorIdProveedor.setEnabled(false);

        jtxtFiltroColoniaProveedor.setText("Colonia");
        jtxtFiltroColoniaProveedor.setEnabled(false);
        jtxtFiltroColoniaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFiltroColoniaProveedorMouseClicked(evt);
            }
        });
        jtxtFiltroColoniaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiltroColoniaProveedorActionPerformed(evt);
            }
        });

        jcmbFiltrarPorSituacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO", " " }));
        jcmbFiltrarPorSituacion.setEnabled(false);

        jtxtFiltroCodigoPostalProveedor.setText("C.P");
        jtxtFiltroCodigoPostalProveedor.setEnabled(false);
        jtxtFiltroCodigoPostalProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFiltroCodigoPostalProveedorMouseClicked(evt);
            }
        });

        buttonGroup1.add(jrbFiltrarPorNombreProveedor);
        jrbFiltrarPorNombreProveedor.setText("Traer por nombre");
        jrbFiltrarPorNombreProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbFiltrarPorNombreProveedorMouseClicked(evt);
            }
        });

        jtxtFiltrarPorNombreProveedor.setEnabled(false);

        jtxtFiltroMunicipioProveedor.setText("Municipio");
        jtxtFiltroMunicipioProveedor.setEnabled(false);
        jtxtFiltroMunicipioProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFiltroMunicipioProveedorMouseClicked(evt);
            }
        });

        jtxtFiltroEstadoProveedor.setText("Estado");
        jtxtFiltroEstadoProveedor.setEnabled(false);
        jtxtFiltroEstadoProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFiltroEstadoProveedorMouseClicked(evt);
            }
        });
        jtxtFiltroEstadoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiltroEstadoProveedorActionPerformed(evt);
            }
        });

        jtxtFiltroCalleProveedor.setText("Calle");
        jtxtFiltroCalleProveedor.setEnabled(false);
        jtxtFiltroCalleProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFiltroCalleProveedorMouseClicked(evt);
            }
        });

        jtxtFiltroNumeroCasaProveedor.setText("Numero");
        jtxtFiltroNumeroCasaProveedor.setEnabled(false);
        jtxtFiltroNumeroCasaProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtFiltroNumeroCasaProveedorMouseClicked(evt);
            }
        });

        btnFiltrarProveedor.setText("FILTRAR");
        btnFiltrarProveedor.setEnabled(false);
        btnFiltrarProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarProveedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbFiltrarTodosLosProveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrbFiltrarAlgunosProveedores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFiltrarAlgunosProveedoresInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFiltrarAlgunosProveedoresFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbFiltrarPorSituacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbFiltrarPorSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbFiltrarPorIdProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtFiltrarPorIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                                .addComponent(jrbFiltrarPorDireccion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jrbFiltrarPorNombreProveedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtFiltrarPorNombreProveedor)
                                .addGap(91, 91, 91)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtFiltroEstadoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtFiltroMunicipioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnFiltrarProveedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jtxtFiltroCalleProveedor)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtxtFiltroNumeroCasaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxtFiltroCodigoPostalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtFiltroColoniaProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFiltrarTodosLosProveedores)
                    .addComponent(jrbFiltrarAlgunosProveedores)
                    .addComponent(jtxtFiltrarAlgunosProveedoresInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFiltrarAlgunosProveedoresFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFiltrarPorIdProveedor)
                    .addComponent(jtxtFiltrarPorIdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrbFiltrarPorDireccion)
                    .addComponent(jtxtFiltroColoniaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFiltroMunicipioProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFiltroEstadoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFiltrarPorSituacion)
                    .addComponent(jcmbFiltrarPorSituacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFiltroCalleProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFiltroNumeroCasaProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFiltroCodigoPostalProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbFiltrarPorNombreProveedor)
                    .addComponent(jtxtFiltrarPorNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrarProveedor))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtMunicipioProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtMunicipioProveedorMouseClicked
        jtxtMunicipioProveedor.setText("");
        if(jtxtMunicipioProveedor.getText().equals("")){
            jtxtMunicipioProveedor.setText("");
        }
        if( jtxtCodigoPostalProveedor.getText().equals("")){

            jtxtCodigoPostalProveedor.setText("  C.P");

        }
        if(jtxtNumeroDeContacto.getText().equals("")){

            jtxtNumeroDeContacto.setText("        NUMERO DE CONTACTO ");

        }
        if(jtxtNombreProveedor.getText().equals("")){

            jtxtNombreProveedor.setText("              NOMBRE");

        }
        if(jtxtEstadoProveedor.getText().equals("")){

            jtxtEstadoProveedor.setText("         ESTADO");

        }
        if(jtxtNumeroCalle.getText().equals("")){

            jtxtNumeroCalle.setText("    NUMERO");

        }
        if(jtxtColoniaProveedor.getText().equals("")){

            jtxtColoniaProveedor.setText("     COLONIA");

        }
        if(jtxtCalleProveedor.getText().equals("")){

            jtxtCalleProveedor.setText("             CALLE");

        }
    }//GEN-LAST:event_jtxtMunicipioProveedorMouseClicked

    private void jtxtNombreProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNombreProveedorMouseClicked
        jtxtNombreProveedor.setText("");
        if(jtxtNombreProveedor.getText().equals("")){
            jtxtNombreProveedor.setText("");
        }
        if( jtxtCodigoPostalProveedor.getText().equals("")){

            jtxtCodigoPostalProveedor.setText("               C.P");

        }
        if(jtxtNumeroDeContacto.getText().equals("")){

            jtxtNumeroDeContacto.setText("        NUMERO DE CONTACTO ");

        }
        if(jtxtMunicipioProveedor.getText().equals("")){

            jtxtMunicipioProveedor.setText("             MUNICIPIO");

        }
        if(jtxtEstadoProveedor.getText().equals("")){

            jtxtEstadoProveedor.setText("         ESTADO");

        }
        if(jtxtNumeroCalle.getText().equals("")){

            jtxtNumeroCalle.setText("        NUMERO");
           
        }
        if(jtxtColoniaProveedor.getText().equals("")){

            jtxtColoniaProveedor.setText("     COLONIA");

        }
        if(jtxtCalleProveedor.getText().equals("")){

            jtxtCalleProveedor.setText("              CALLE");

        }

    }//GEN-LAST:event_jtxtNombreProveedorMouseClicked

    private void jtxtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreProveedorActionPerformed

    private void jtxtCodigoPostalProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCodigoPostalProveedorMouseClicked
        jtxtCodigoPostalProveedor.setText("");
        if(jtxtCodigoPostalProveedor.getText().equals("")){
            jtxtCodigoPostalProveedor.setText("");
        }
        if( jtxtNombreProveedor.getText().equals("")){

            jtxtNombreProveedor.setText("                 NOMBRE");

        }
        if(jtxtNumeroDeContacto.getText().equals("")){

            jtxtNumeroDeContacto.setText("        NUMERO DE CONTACTO ");

        }
        if(jtxtMunicipioProveedor.getText().equals("")){

            jtxtMunicipioProveedor.setText("          MUNICIPIO");

        }
        if(jtxtEstadoProveedor.getText().equals("")){

            jtxtEstadoProveedor.setText("         ESTADO");

        }
        if(jtxtNumeroCalle.getText().equals("")){

            jtxtNumeroCalle.setText("    NUMERO");

        }
        if(jtxtColoniaProveedor.getText().equals("")){

            jtxtColoniaProveedor.setText("             COLONIA");

        }
        if(jtxtCalleProveedor.getText().equals("")){

            jtxtCalleProveedor.setText("                CALLE");

        }

    }//GEN-LAST:event_jtxtCodigoPostalProveedorMouseClicked

    private void jtxtNumeroDeContactoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNumeroDeContactoMouseClicked
        jtxtNumeroDeContacto.setText("");
        if(jtxtNumeroDeContacto.getText().equals("")){
            jtxtNumeroDeContacto.setText("");
        }
        if( jtxtCodigoPostalProveedor.getText().equals("")){

            jtxtCodigoPostalProveedor.setText("           C.P");

        }
        if(jtxtNombreProveedor.getText().equals("")){

            jtxtNombreProveedor.setText("                    NOMBRE");

        }
        if(jtxtMunicipioProveedor.getText().equals("")){

            jtxtMunicipioProveedor.setText("            MUNICIPIO");

        }
        if(jtxtEstadoProveedor.getText().equals("")){

            jtxtEstadoProveedor.setText("         ESTADO");

        }
        if(jtxtNumeroCalle.getText().equals("")){

            jtxtNumeroCalle.setText("     NUMERO");

        }
        if(jtxtColoniaProveedor.getText().equals("")){

            jtxtColoniaProveedor.setText("             COLONIA");

        }
        if(jtxtCalleProveedor.getText().equals("")){

            jtxtCalleProveedor.setText("                 CALLE");

        }
       
    }//GEN-LAST:event_jtxtNumeroDeContactoMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked

        ps.cancelarEdicionProveedores(this);

    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnInsertarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarProveedorMouseClicked

        boolean estadoCampos;    
        this.proveedor = new Proveedor();
    
        estadoCampos = this.ps.obtenerInformacion(this);
        
        if(estadoCampos == false)
        {
            
          JOptionPane.showMessageDialog(null, "Inserta Información verídica");
            
        }else
        {
        
          this.ps.agregarRegistroProveedor(this);
        
        }


    }//GEN-LAST:event_btnInsertarProveedorMouseClicked

    private void btnModiificarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModiificarProveedorMouseClicked

        ps.modificarProveedor(this);

    }//GEN-LAST:event_btnModiificarProveedorMouseClicked

    private void btnModiificarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiificarProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModiificarProveedorActionPerformed

    private void jtxtCodigoPostalProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCodigoPostalProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCodigoPostalProveedorActionPerformed

    private void jtxtColoniaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtColoniaProveedorMouseClicked
         jtxtColoniaProveedor.setText("");
        if(jtxtColoniaProveedor.getText().equals("")){
            jtxtColoniaProveedor.setText("");
        }
        if( jtxtCodigoPostalProveedor.getText().equals("")){

            jtxtCodigoPostalProveedor.setText("              C.P");

        }
        if(jtxtNombreProveedor.getText().equals("")){

            jtxtNombreProveedor.setText("                    NOMBRE");

        }
        if(jtxtMunicipioProveedor.getText().equals("")){

            jtxtMunicipioProveedor.setText("            MUNICIPIO");

        }
        if(jtxtEstadoProveedor.getText().equals("")){

            jtxtEstadoProveedor.setText("         ESTADO");

        }
       
        if(jtxtNumeroCalle.getText().equals("")){

            jtxtNumeroCalle.setText("        NUMERO");

        }
        if(jtxtCalleProveedor.getText().equals("")){

            jtxtCalleProveedor.setText("           CALLE");

        }
        if(jtxtNumeroDeContacto.getText().equals("")){

            jtxtNumeroDeContacto.setText("        NUMERO DE CONTACTO ");

        }
    }//GEN-LAST:event_jtxtColoniaProveedorMouseClicked

    private void jtxtColoniaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtColoniaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtColoniaProveedorActionPerformed

    private void jtxtCalleProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtCalleProveedorMouseClicked
        jtxtCalleProveedor.setText("");
        if(jtxtCalleProveedor.getText().equals("")){
            jtxtCalleProveedor.setText("");
        }
        if( jtxtCodigoPostalProveedor.getText().equals("")){

            jtxtCodigoPostalProveedor.setText("              C.P");

        }
        if(jtxtNombreProveedor.getText().equals("")){

            jtxtNombreProveedor.setText("                    NOMBRE");

        }
        if(jtxtMunicipioProveedor.getText().equals("")){

            jtxtMunicipioProveedor.setText("            MUNICIPIO");

        }
        if(jtxtEstadoProveedor.getText().equals("")){

            jtxtEstadoProveedor.setText("         ESTADO");

        }
       
        if(jtxtNumeroCalle.getText().equals("")){

            jtxtNumeroCalle.setText("    NUMERO");

        }
        if(jtxtColoniaProveedor.getText().equals("")){

            jtxtColoniaProveedor.setText("             COLONIA");

        }
        if(jtxtNumeroDeContacto.getText().equals("")){

            jtxtNumeroDeContacto.setText("        NUMERO DE CONTACTO ");

        }
    }//GEN-LAST:event_jtxtCalleProveedorMouseClicked

    private void jtxtCalleProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCalleProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCalleProveedorActionPerformed

    private void jtxtNumeroCalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNumeroCalleMouseClicked
         jtxtNumeroCalle.setText("");
         if(jtxtNumeroCalle.getText().equals("")){
            jtxtNumeroCalle.setText("");
        }
        if( jtxtCodigoPostalProveedor.getText().equals("")){

            jtxtCodigoPostalProveedor.setText("          C.P");

        }
        if(jtxtCalleProveedor.getText().equals("")){

            jtxtCalleProveedor.setText("            CALLE");

        }
        if(jtxtMunicipioProveedor.getText().equals("")){

            jtxtMunicipioProveedor.setText("            MUNICIPIO");

        }
        if(jtxtEstadoProveedor.getText().equals("")){

            jtxtEstadoProveedor.setText("         ESTADO");

        }
       
        if(jtxtNombreProveedor.getText().equals("")){

            jtxtNombreProveedor.setText("           NOMBRE");

        }
        if(jtxtColoniaProveedor.getText().equals("")){

            jtxtColoniaProveedor.setText("     COLONIA");

        }
        if(jtxtNumeroDeContacto.getText().equals("")){

            jtxtNumeroDeContacto.setText("        NUMERO DE CONTACTO ");

        }
        
    }//GEN-LAST:event_jtxtNumeroCalleMouseClicked

    private void jtxtNumeroCalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumeroCalleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumeroCalleActionPerformed

    private void jtxtMunicipioProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMunicipioProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMunicipioProveedorActionPerformed

    private void jtxtEstadoProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtEstadoProveedorMouseClicked
        jtxtEstadoProveedor.setText("");
        if(jtxtEstadoProveedor.getText().equals("")){
            jtxtEstadoProveedor.setText("");
        }
        if( jtxtCodigoPostalProveedor.getText().equals("")){

            jtxtCodigoPostalProveedor.setText("   C.P");

        }
        if(jtxtNombreProveedor.getText().equals("")){

            jtxtNombreProveedor.setText("                    NOMBRE");

        }
        if(jtxtMunicipioProveedor.getText().equals("")){

            jtxtMunicipioProveedor.setText("            MUNICIPIO");

        }
        if(jtxtCalleProveedor.getText().equals("")){

            jtxtCalleProveedor.setText("         CALLE");

        }
       
        if(jtxtNumeroCalle.getText().equals("")){

            jtxtNumeroCalle.setText("    NUMERO");

        }
        if(jtxtColoniaProveedor.getText().equals("")){

            jtxtColoniaProveedor.setText("     COLONIA");

        }
        if(jtxtNumeroDeContacto.getText().equals("")){

            jtxtNumeroDeContacto.setText("        NUMERO DE CONTACTO ");

        }
    }//GEN-LAST:event_jtxtEstadoProveedorMouseClicked

    private void jtxtEstadoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEstadoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEstadoProveedorActionPerformed

    private void jtblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProveedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jtblProveedoresMouseClicked

    private void jtxtFiltroColoniaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiltroColoniaProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiltroColoniaProveedorActionPerformed

    private void jtxtFiltroEstadoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiltroEstadoProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiltroEstadoProveedorActionPerformed

    private void jtxtFiltrarAlgunosProveedoresInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiltrarAlgunosProveedoresInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiltrarAlgunosProveedoresInicialActionPerformed

    private void jrbFiltrarTodosLosProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFiltrarTodosLosProveedoresMouseClicked
        
        proveedor = new Proveedor();
        this.btnFiltrarProveedor.setEnabled(true);
        this.jcmbFiltrarPorSituacion.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setText("");
        this.jtxtFiltrarAlgunosProveedoresInicial.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresInicial.setText("");
        this.jtxtFiltrarPorIdProveedor.setEnabled(false);
        this.jtxtFiltrarPorIdProveedor.setText("");
        this.jtxtFiltrarPorNombreProveedor.setEnabled(false);
        this.jtxtFiltrarPorNombreProveedor.setText("");
        this.jtxtFiltroCalleProveedor.setEnabled(false);
        this.jtxtFiltroCalleProveedor.setText("Calle");
        this.jtxtFiltroCodigoPostalProveedor.setEnabled(false);
        this.jtxtFiltroCodigoPostalProveedor.setText("C.P");
        this.jtxtFiltroColoniaProveedor.setEnabled(false);
        this.jtxtFiltroColoniaProveedor.setText("Colonia");
        this.jtxtFiltroEstadoProveedor.setEnabled(false);
        this.jtxtFiltroEstadoProveedor.setText("Estado");
        this.jtxtFiltroMunicipioProveedor.setEnabled(false);
        this.jtxtFiltroMunicipioProveedor.setText("Municipio");
        this.jtxtFiltroNumeroCasaProveedor.setEnabled(false);
        this.jtxtFiltroNumeroCasaProveedor.setText("Numero");

    }//GEN-LAST:event_jrbFiltrarTodosLosProveedoresMouseClicked

    private void jrbFiltrarAlgunosProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFiltrarAlgunosProveedoresMouseClicked

        proveedor = new Proveedor();
        this.btnFiltrarProveedor.setEnabled(true);
        this.jcmbFiltrarPorSituacion.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setEnabled(true);
        this.jtxtFiltrarAlgunosProveedoresInicial.setEnabled(true);
        this.jtxtFiltrarPorIdProveedor.setEnabled(false);
        this.jtxtFiltrarPorIdProveedor.setText("");
        this.jtxtFiltrarPorNombreProveedor.setEnabled(false);
        this.jtxtFiltrarPorNombreProveedor.setText("");
        this.jtxtFiltroCalleProveedor.setEnabled(false);
        this.jtxtFiltroCalleProveedor.setText("Calle");
        this.jtxtFiltroCodigoPostalProveedor.setEnabled(false);
        this.jtxtFiltroCodigoPostalProveedor.setText("C.P");
        this.jtxtFiltroColoniaProveedor.setEnabled(false);
        this.jtxtFiltroColoniaProveedor.setText("Colonia");
        this.jtxtFiltroEstadoProveedor.setEnabled(false);
        this.jtxtFiltroEstadoProveedor.setText("Estado");
        this.jtxtFiltroMunicipioProveedor.setEnabled(false);
        this.jtxtFiltroMunicipioProveedor.setText("Municipio");
        this.jtxtFiltroNumeroCasaProveedor.setEnabled(false);
        this.jtxtFiltroNumeroCasaProveedor.setText("Numero");

    }//GEN-LAST:event_jrbFiltrarAlgunosProveedoresMouseClicked

    private void jrbFiltrarPorIdProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFiltrarPorIdProveedorMouseClicked

        proveedor = new Proveedor();
        this.btnFiltrarProveedor.setEnabled(true);
        this.jcmbFiltrarPorSituacion.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setText("");
        this.jtxtFiltrarAlgunosProveedoresInicial.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresInicial.setText("");
        this.jtxtFiltrarPorIdProveedor.setEnabled(true);
        this.jtxtFiltrarPorNombreProveedor.setEnabled(false);
        this.jtxtFiltrarPorNombreProveedor.setText("");
        this.jtxtFiltroCalleProveedor.setEnabled(false);
        this.jtxtFiltroCalleProveedor.setText("Calle");
        this.jtxtFiltroCodigoPostalProveedor.setEnabled(false);
        this.jtxtFiltroCodigoPostalProveedor.setText("C.P");
        this.jtxtFiltroColoniaProveedor.setEnabled(false);
        this.jtxtFiltroColoniaProveedor.setText("Colonia");
        this.jtxtFiltroEstadoProveedor.setEnabled(false);
        this.jtxtFiltroEstadoProveedor.setText("Estado");
        this.jtxtFiltroMunicipioProveedor.setEnabled(false);
        this.jtxtFiltroMunicipioProveedor.setText("Municipio");
        this.jtxtFiltroNumeroCasaProveedor.setEnabled(false);
        this.jtxtFiltroNumeroCasaProveedor.setText("Numero");

    }//GEN-LAST:event_jrbFiltrarPorIdProveedorMouseClicked

    private void jrbFiltrarPorSituacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFiltrarPorSituacionMouseClicked

        proveedor = new Proveedor();
        this.btnFiltrarProveedor.setEnabled(true);
        this.jcmbFiltrarPorSituacion.setEnabled(true);
        this.jtxtFiltrarAlgunosProveedoresFinal.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setText("");
        this.jtxtFiltrarAlgunosProveedoresInicial.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresInicial.setText("");
        this.jtxtFiltrarPorIdProveedor.setEnabled(false);
        this.jtxtFiltrarPorIdProveedor.setText("");
        this.jtxtFiltrarPorNombreProveedor.setEnabled(false);
        this.jtxtFiltrarPorNombreProveedor.setText("");
        this.jtxtFiltroCalleProveedor.setEnabled(false);
        this.jtxtFiltroCalleProveedor.setText("Calle");
        this.jtxtFiltroCodigoPostalProveedor.setEnabled(false);
        this.jtxtFiltroCodigoPostalProveedor.setText("C.P");
        this.jtxtFiltroColoniaProveedor.setEnabled(false);
        this.jtxtFiltroColoniaProveedor.setText("Colonia");
        this.jtxtFiltroEstadoProveedor.setEnabled(false);
        this.jtxtFiltroEstadoProveedor.setText("Estado");
        this.jtxtFiltroMunicipioProveedor.setEnabled(false);
        this.jtxtFiltroMunicipioProveedor.setText("Municipio");
        this.jtxtFiltroNumeroCasaProveedor.setEnabled(false);
        this.jtxtFiltroNumeroCasaProveedor.setText("Numero");

    }//GEN-LAST:event_jrbFiltrarPorSituacionMouseClicked

    private void jrbFiltrarPorNombreProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFiltrarPorNombreProveedorMouseClicked

        proveedor = new Proveedor();
        this.btnFiltrarProveedor.setEnabled(true);
        this.jcmbFiltrarPorSituacion.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setText("");
        this.jtxtFiltrarAlgunosProveedoresInicial.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresInicial.setText("");
        this.jtxtFiltrarPorIdProveedor.setEnabled(false);
        this.jtxtFiltrarPorIdProveedor.setText("");
        this.jtxtFiltrarPorNombreProveedor.setEnabled(true);
        this.jtxtFiltroCalleProveedor.setEnabled(false);
        this.jtxtFiltroCalleProveedor.setText("Calle");
        this.jtxtFiltroCodigoPostalProveedor.setEnabled(false);
        this.jtxtFiltroCodigoPostalProveedor.setText("C.P");
        this.jtxtFiltroColoniaProveedor.setEnabled(false);
        this.jtxtFiltroColoniaProveedor.setText("Colonia");
        this.jtxtFiltroEstadoProveedor.setEnabled(false);
        this.jtxtFiltroEstadoProveedor.setText("Estado");
        this.jtxtFiltroMunicipioProveedor.setEnabled(false);
        this.jtxtFiltroMunicipioProveedor.setText("Municipio");
        this.jtxtFiltroNumeroCasaProveedor.setEnabled(false);
        this.jtxtFiltroNumeroCasaProveedor.setText("Numero");

    }//GEN-LAST:event_jrbFiltrarPorNombreProveedorMouseClicked

    private void jrbFiltrarPorDireccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbFiltrarPorDireccionMouseClicked

        proveedor = new Proveedor();
        this.btnFiltrarProveedor.setEnabled(true);
        this.jcmbFiltrarPorSituacion.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresFinal.setText("");
        this.jtxtFiltrarAlgunosProveedoresInicial.setEnabled(false);
        this.jtxtFiltrarAlgunosProveedoresInicial.setText("");
        this.jtxtFiltrarPorIdProveedor.setEnabled(false);
        this.jtxtFiltrarPorIdProveedor.setText("");
        this.jtxtFiltrarPorNombreProveedor.setEnabled(false);
        this.jtxtFiltrarPorNombreProveedor.setText("");
        this.jtxtFiltroCalleProveedor.setEnabled(true);
        this.jtxtFiltroCalleProveedor.setText("Calle");
        this.jtxtFiltroCodigoPostalProveedor.setEnabled(true);
        this.jtxtFiltroCodigoPostalProveedor.setText("C.P");
        this.jtxtFiltroColoniaProveedor.setEnabled(true);
        this.jtxtFiltroColoniaProveedor.setText("Colonia");
        this.jtxtFiltroEstadoProveedor.setEnabled(true);
        this.jtxtFiltroEstadoProveedor.setText("Estado");
        this.jtxtFiltroMunicipioProveedor.setEnabled(true);
        this.jtxtFiltroMunicipioProveedor.setText("Municipio");
        this.jtxtFiltroNumeroCasaProveedor.setEnabled(true);
        this.jtxtFiltroNumeroCasaProveedor.setText("Numero");


    }//GEN-LAST:event_jrbFiltrarPorDireccionMouseClicked

    private void jtxtFiltroEstadoProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFiltroEstadoProveedorMouseClicked

        if(this.jrbFiltrarPorDireccion.isSelected())
        {
            this.jtxtFiltroEstadoProveedor.setText("");
        }

    }//GEN-LAST:event_jtxtFiltroEstadoProveedorMouseClicked

    private void jtxtFiltroMunicipioProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFiltroMunicipioProveedorMouseClicked
        
        if(this.jrbFiltrarPorDireccion.isSelected())
        {
            
            this.jtxtFiltroMunicipioProveedor.setText("");
            
        }
        
        
    }//GEN-LAST:event_jtxtFiltroMunicipioProveedorMouseClicked

    private void jtxtFiltroColoniaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFiltroColoniaProveedorMouseClicked

        if(this.jrbFiltrarPorDireccion.isSelected())
        {
            
            this.jtxtFiltroColoniaProveedor.setText("");
            
        }

    }//GEN-LAST:event_jtxtFiltroColoniaProveedorMouseClicked

    private void jtxtFiltroCalleProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFiltroCalleProveedorMouseClicked

        if(this.jrbFiltrarPorDireccion.isSelected())
        {
            
            this.jtxtFiltroCalleProveedor.setText("");
            
        }
        
    }//GEN-LAST:event_jtxtFiltroCalleProveedorMouseClicked

    private void jtxtFiltroNumeroCasaProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFiltroNumeroCasaProveedorMouseClicked

        if(this.jrbFiltrarPorDireccion.isSelected())
        {
            
            this.jtxtFiltroNumeroCasaProveedor.setText("");
            
        }

    }//GEN-LAST:event_jtxtFiltroNumeroCasaProveedorMouseClicked

    private void jtxtFiltroCodigoPostalProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtFiltroCodigoPostalProveedorMouseClicked

        if(this.jrbFiltrarPorDireccion.isSelected())
        {
            
            this.jtxtFiltroCodigoPostalProveedor.setText("");
            
        }

    }//GEN-LAST:event_jtxtFiltroCodigoPostalProveedorMouseClicked

    private void btnFiltrarProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarProveedorMouseClicked

        this.ps.consultar(this);

    }//GEN-LAST:event_btnFiltrarProveedorMouseClicked

    public Proveedor getProveedor() {
        return proveedor;
    }

    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public JComboBox<String> getJcmbFiltrarPorSituacion() {
        return jcmbFiltrarPorSituacion;
    }

    public void setJcmbFiltrarPorSituacion(JComboBox<String> jcmbFiltrarPorSituacion) {
        this.jcmbFiltrarPorSituacion = jcmbFiltrarPorSituacion;
    }

    public JComboBox<String> getJcmbSituacionProveedor() {
        return jcmbSituacionProveedor;
    }

    public void setJcmbSituacionProveedor(JComboBox<String> jcmbSituacionProveedor) {
        this.jcmbSituacionProveedor = jcmbSituacionProveedor;
    }


    public JRadioButton getJrbFiltrarAlgunosProveedores() {
        return jrbFiltrarAlgunosProveedores;
    }

    public void setJrbFiltrarAlgunosProveedores(JRadioButton jrbFiltrarAlgunosProveedores) {
        this.jrbFiltrarAlgunosProveedores = jrbFiltrarAlgunosProveedores;
    }

    public JRadioButton getJrbFiltrarPorDireccion() {
        return jrbFiltrarPorDireccion;
    }

    public void setJrbFiltrarPorDireccion(JRadioButton jrbFiltrarPorDireccion) {
        this.jrbFiltrarPorDireccion = jrbFiltrarPorDireccion;
    }

    public JRadioButton getJrbFiltrarPorIdProveedor() {
        return jrbFiltrarPorIdProveedor;
    }

    public void setJrbFiltrarPorIdProveedor(JRadioButton jrbFiltrarPorIdProveedor) {
        this.jrbFiltrarPorIdProveedor = jrbFiltrarPorIdProveedor;
    }

    public JRadioButton getJrbFiltrarPorNombreProveedor() {
        return jrbFiltrarPorNombreProveedor;
    }

    public void setJrbFiltrarPorNombreProveedor(JRadioButton jrbFiltrarPorNombreProveedor) {
        this.jrbFiltrarPorNombreProveedor = jrbFiltrarPorNombreProveedor;
    }

    public JRadioButton getJrbFiltrarPorSituacion() {
        return jrbFiltrarPorSituacion;
    }

    public void setJrbFiltrarPorSituacion(JRadioButton jrbFiltrarPorSituacion) {
        this.jrbFiltrarPorSituacion = jrbFiltrarPorSituacion;
    }

    public JRadioButton getJrbFiltrarTodosLosProveedores() {
        return jrbFiltrarTodosLosProveedores;
    }

    public void setJrbFiltrarTodosLosProveedores(JRadioButton jrbFiltrarTodosLosProveedores) {
        this.jrbFiltrarTodosLosProveedores = jrbFiltrarTodosLosProveedores;
    }

    public JTable getJtblProveedores() {
        return jtblProveedores;
    }

    public void setJtblProveedores(JTable jtblProveedores) {
        this.jtblProveedores = jtblProveedores;
    }

    public JTextField getJtxtCalleProveedor() {
        return jtxtCalleProveedor;
    }

    public void setJtxtCalleProveedor(JTextField jtxtCalleProveedor) {
        this.jtxtCalleProveedor = jtxtCalleProveedor;
    }

    public JTextField getJtxtCodigoPostalProveedor() {
        return jtxtCodigoPostalProveedor;
    }

    public void setJtxtCodigoPostalProveedor(JTextField jtxtCodigoPostalProveedor) {
        this.jtxtCodigoPostalProveedor = jtxtCodigoPostalProveedor;
    }

    public JTextField getJtxtColoniaProveedor() {
        return jtxtColoniaProveedor;
    }

    public void setJtxtColoniaProveedor(JTextField jtxtColoniaProveedor) {
        this.jtxtColoniaProveedor = jtxtColoniaProveedor;
    }

    public JTextField getJtxtEstadoProveedor() {
        return jtxtEstadoProveedor;
    }

    public void setJtxtEstadoProveedor(JTextField jtxtEstadoProveedor) {
        this.jtxtEstadoProveedor = jtxtEstadoProveedor;
    }

    public JTextField getJtxtFiltrarAlgunosProveedoresFinal() {
        return jtxtFiltrarAlgunosProveedoresFinal;
    }

    public void setJtxtFiltrarAlgunosProveedoresFinal(JTextField jtxtFiltrarAlgunosProveedoresFinal) {
        this.jtxtFiltrarAlgunosProveedoresFinal = jtxtFiltrarAlgunosProveedoresFinal;
    }

    public JTextField getJtxtFiltrarAlgunosProveedoresInicial() {
        return jtxtFiltrarAlgunosProveedoresInicial;
    }

    public void setJtxtFiltrarAlgunosProveedoresInicial(JTextField jtxtFiltrarAlgunosProveedoresInicial) {
        this.jtxtFiltrarAlgunosProveedoresInicial = jtxtFiltrarAlgunosProveedoresInicial;
    }

    public JTextField getJtxtFiltrarPorIdProveedor() {
        return jtxtFiltrarPorIdProveedor;
    }

    public void setJtxtFiltrarPorIdProveedor(JTextField jtxtFiltrarPorIdProveedor) {
        this.jtxtFiltrarPorIdProveedor = jtxtFiltrarPorIdProveedor;
    }

    public JTextField getJtxtFiltrarPorNombreProveedor() {
        return jtxtFiltrarPorNombreProveedor;
    }

    public void setJtxtFiltrarPorNombreProveedor(JTextField jtxtFiltrarPorNombreProveedor) {
        this.jtxtFiltrarPorNombreProveedor = jtxtFiltrarPorNombreProveedor;
    }

    public JTextField getJtxtFiltroCalleProveedor() {
        return jtxtFiltroCalleProveedor;
    }

    public void setJtxtFiltroCalleProveedor(JTextField jtxtFiltroCalleProveedor) {
        this.jtxtFiltroCalleProveedor = jtxtFiltroCalleProveedor;
    }

    public JTextField getJtxtFiltroCodigoPostalProveedor() {
        return jtxtFiltroCodigoPostalProveedor;
    }

    public void setJtxtFiltroCodigoPostalProveedor(JTextField jtxtFiltroCodigoPostalProveedor) {
        this.jtxtFiltroCodigoPostalProveedor = jtxtFiltroCodigoPostalProveedor;
    }

    public JTextField getJtxtFiltroColoniaProveedor() {
        return jtxtFiltroColoniaProveedor;
    }

    public void setJtxtFiltroColoniaProveedor(JTextField jtxtFiltroColoniaProveedor) {
        this.jtxtFiltroColoniaProveedor = jtxtFiltroColoniaProveedor;
    }

    public JTextField getJtxtFiltroEstadoProveedor() {
        return jtxtFiltroEstadoProveedor;
    }

    public void setJtxtFiltroEstadoProveedor(JTextField jtxtFiltroEstadoProveedor) {
        this.jtxtFiltroEstadoProveedor = jtxtFiltroEstadoProveedor;
    }

    public JTextField getJtxtFiltroMunicipioProveedor() {
        return jtxtFiltroMunicipioProveedor;
    }

    public void setJtxtFiltroMunicipioProveedor(JTextField jtxtFiltroMunicipioProveedor) {
        this.jtxtFiltroMunicipioProveedor = jtxtFiltroMunicipioProveedor;
    }

    public JTextField getJtxtFiltroNumeroCasaProveedor() {
        return jtxtFiltroNumeroCasaProveedor;
    }

    public void setJtxtFiltroNumeroCasaProveedor(JTextField jtxtFiltroNumeroCasaProveedor) {
        this.jtxtFiltroNumeroCasaProveedor = jtxtFiltroNumeroCasaProveedor;
    }

    public JTextField getJtxtMunicipioProveedor() {
        return jtxtMunicipioProveedor;
    }

    public void setJtxtMunicipioProveedor(JTextField jtxtMunicipioProveedor) {
        this.jtxtMunicipioProveedor = jtxtMunicipioProveedor;
    }

    public JTextField getJtxtNombreProveedor() {
        return jtxtNombreProveedor;
    }

    public void setJtxtNombreProveedor(JTextField jtxtNombreProveedor) {
        this.jtxtNombreProveedor = jtxtNombreProveedor;
    }

    public JTextField getJtxtNumeroCalle() {
        return jtxtNumeroCalle;
    }

    public void setJtxtNumeroCalle(JTextField jtxtNumeroCalle) {
        this.jtxtNumeroCalle = jtxtNumeroCalle;
    }

    public JTextField getJtxtNumeroDeContacto() {
        return jtxtNumeroDeContacto;
    }

    public void setJtxtNumeroDeContacto(JTextField jtxtNumeroDeContacto) {
        this.jtxtNumeroDeContacto = jtxtNumeroDeContacto;
    }

    public JButton getBtnFiltrarProveedor() {
        return btnFiltrarProveedor;
    }

    public void setBtnFiltrarProveedor(JButton btnFiltrarProveedor) {
        this.btnFiltrarProveedor = btnFiltrarProveedor;
    }

    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnFiltrarProveedor;
    private javax.swing.JButton btnInsertarProveedor;
    private javax.swing.JButton btnModiificarProveedor;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcmbFiltrarPorSituacion;
    private javax.swing.JComboBox<String> jcmbSituacionProveedor;
    private javax.swing.JRadioButton jrbFiltrarAlgunosProveedores;
    private javax.swing.JRadioButton jrbFiltrarPorDireccion;
    private javax.swing.JRadioButton jrbFiltrarPorIdProveedor;
    private javax.swing.JRadioButton jrbFiltrarPorNombreProveedor;
    private javax.swing.JRadioButton jrbFiltrarPorSituacion;
    private javax.swing.JRadioButton jrbFiltrarTodosLosProveedores;
    private javax.swing.JTable jtblProveedores;
    private javax.swing.JTextField jtxtCalleProveedor;
    private javax.swing.JTextField jtxtCodigoPostalProveedor;
    private javax.swing.JTextField jtxtColoniaProveedor;
    private javax.swing.JTextField jtxtEstadoProveedor;
    private javax.swing.JTextField jtxtFiltrarAlgunosProveedoresFinal;
    private javax.swing.JTextField jtxtFiltrarAlgunosProveedoresInicial;
    private javax.swing.JTextField jtxtFiltrarPorIdProveedor;
    private javax.swing.JTextField jtxtFiltrarPorNombreProveedor;
    private javax.swing.JTextField jtxtFiltroCalleProveedor;
    private javax.swing.JTextField jtxtFiltroCodigoPostalProveedor;
    private javax.swing.JTextField jtxtFiltroColoniaProveedor;
    private javax.swing.JTextField jtxtFiltroEstadoProveedor;
    private javax.swing.JTextField jtxtFiltroMunicipioProveedor;
    private javax.swing.JTextField jtxtFiltroNumeroCasaProveedor;
    private javax.swing.JTextField jtxtMunicipioProveedor;
    private javax.swing.JTextField jtxtNombreProveedor;
    private javax.swing.JTextField jtxtNumeroCalle;
    private javax.swing.JTextField jtxtNumeroDeContacto;
    // End of variables declaration//GEN-END:variables
}
