/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Reportes;
import Modelo.Reporte;
import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author marco
 */
public class ModuloReportes extends javax.swing.JPanel {

    /**
     * Creates new form ModuloReportes
     */
    public ModuloReportes() {
        initComponents();
    }

    
    Reporte reporte;
    Reportes rp = new Reportes();
    boolean activar = false;
    int contador = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelarGenerar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jdtFechaInicial = new com.toedter.calendar.JDateChooser();
        jdtFechaFinal = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnAnteriorGrafica = new javax.swing.JButton();
        btnSiguienteGrafica = new javax.swing.JButton();
        jpnlMAV = new javax.swing.JPanel();
        jpnlMEV = new javax.swing.JPanel();
        jpnlAPT = new javax.swing.JPanel();
        jpnlGST = new javax.swing.JPanel();
        jpnlGNS = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(78, 137, 117));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RANGO FINAL DE FECHA");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("RANGO INICIO DE FECHA");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 29));

        btnCancelarGenerar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnCancelarGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarGenerar.setText("CANCELAR");
        btnCancelarGenerar.setBorder(null);
        btnCancelarGenerar.setBorderPainted(false);
        btnCancelarGenerar.setContentAreaFilled(false);
        btnCancelarGenerar.setFocusPainted(false);
        btnCancelarGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarGenerarMouseClicked(evt);
            }
        });
        btnCancelarGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGenerarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 40));

        btnGenerar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("GENERAR");
        btnGenerar.setBorder(null);
        btnGenerar.setBorderPainted(false);
        btnGenerar.setContentAreaFilled(false);
        btnGenerar.setFocusPainted(false);
        btnGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGenerarMouseClicked(evt);
            }
        });
        jPanel2.add(btnGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 100, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 250, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 250, 20));

        jdtFechaInicial.setMaxSelectableDate(new java.util.Date(2556169303000L));
        jdtFechaInicial.setMinSelectableDate(new java.util.Date(1609484503000L));
        jPanel2.add(jdtFechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 130, -1));

        jdtFechaFinal.setMaxSelectableDate(new java.util.Date(2556169303000L));
        jdtFechaFinal.setMinSelectableDate(new java.util.Date(1609484503000L));
        jPanel2.add(jdtFechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 270, 590));

        jPanel3.setBackground(new java.awt.Color(63, 50, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 590));

        jPanel4.setBackground(new java.awt.Color(5, 101, 113));

        btnAnteriorGrafica.setText("Anterior");
        btnAnteriorGrafica.setBorder(null);
        btnAnteriorGrafica.setContentAreaFilled(false);
        btnAnteriorGrafica.setEnabled(false);
        btnAnteriorGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnteriorGraficaMouseClicked(evt);
            }
        });

        btnSiguienteGrafica.setText("Siguiente");
        btnSiguienteGrafica.setBorder(null);
        btnSiguienteGrafica.setBorderPainted(false);
        btnSiguienteGrafica.setContentAreaFilled(false);
        btnSiguienteGrafica.setEnabled(false);
        btnSiguienteGrafica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSiguienteGraficaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addComponent(btnAnteriorGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnSiguienteGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSiguienteGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnteriorGrafica, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 510, 820, 80));

        jpnlMAV.setPreferredSize(new java.awt.Dimension(800, 510));

        javax.swing.GroupLayout jpnlMAVLayout = new javax.swing.GroupLayout(jpnlMAV);
        jpnlMAV.setLayout(jpnlMAVLayout);
        jpnlMAVLayout.setHorizontalGroup(
            jpnlMAVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpnlMAVLayout.setVerticalGroup(
            jpnlMAVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jpnlMAV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 0, -1, -1));

        jpnlMEV.setPreferredSize(new java.awt.Dimension(800, 510));

        javax.swing.GroupLayout jpnlMEVLayout = new javax.swing.GroupLayout(jpnlMEV);
        jpnlMEV.setLayout(jpnlMEVLayout);
        jpnlMEVLayout.setHorizontalGroup(
            jpnlMEVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpnlMEVLayout.setVerticalGroup(
            jpnlMEVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jpnlMEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(1610, 0, -1, -1));

        jpnlAPT.setPreferredSize(new java.awt.Dimension(820, 510));

        javax.swing.GroupLayout jpnlAPTLayout = new javax.swing.GroupLayout(jpnlAPT);
        jpnlAPT.setLayout(jpnlAPTLayout);
        jpnlAPTLayout.setHorizontalGroup(
            jpnlAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jpnlAPTLayout.setVerticalGroup(
            jpnlAPTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jpnlAPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1615, 0, -1, -1));

        jpnlGST.setPreferredSize(new java.awt.Dimension(800, 510));

        javax.swing.GroupLayout jpnlGSTLayout = new javax.swing.GroupLayout(jpnlGST);
        jpnlGST.setLayout(jpnlGSTLayout);
        jpnlGSTLayout.setHorizontalGroup(
            jpnlGSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpnlGSTLayout.setVerticalGroup(
            jpnlGSTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jpnlGST, new org.netbeans.lib.awtextra.AbsoluteConstraints(1620, 0, -1, -1));

        jpnlGNS.setPreferredSize(new java.awt.Dimension(820, 510));

        javax.swing.GroupLayout jpnlGNSLayout = new javax.swing.GroupLayout(jpnlGNS);
        jpnlGNS.setLayout(jpnlGNSLayout);
        jpnlGNSLayout.setHorizontalGroup(
            jpnlGNSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        jpnlGNSLayout.setVerticalGroup(
            jpnlGNSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        jPanel1.add(jpnlGNS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1625, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1304, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarGenerarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarGenerarMouseClicked

    private void btnCancelarGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGenerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarGenerarActionPerformed

    private void btnGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGenerarMouseClicked
 
        reporte = new Reporte();
            boolean des;
            
            des = this.rp.obtenerInformacion(this);
           
            if(des == true)
            {
            
                this.rp.generarReporte(this);
                this.activar = true;
                
            }
            
    }//GEN-LAST:event_btnGenerarMouseClicked

    private void btnAnteriorGraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnteriorGraficaMouseClicked

        if(this.contador > 0)
        {

            if(this.contador == 5)
            {
            
                this.rp.moverPanelGNS(this);
                this.rp.moverPanelGST(this);
                this.contador--;
                
            }else if(this.contador == 4)
            {
            
                this.rp.moverPanelGST(this);
                this.rp.moverPanelAPT(this);
                this.contador--;
                
            }else if(this.contador == 3)
            {
                
                this.rp.moverPanelAPT(this);
                this.rp.moverPanelMEV(this);
                this.contador--;
                
            }else if(this.contador == 2)
            {
                
                this.rp.moverPanelMEV(this);
                this.rp.moverPanelMAV(this);
                this.contador--;
                
            }else if(this.contador == 1)
            {
                
                this.rp.moverPanelMAV(this);
                this.contador--;
            }
            
            
        }


    }//GEN-LAST:event_btnAnteriorGraficaMouseClicked

    private void btnSiguienteGraficaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSiguienteGraficaMouseClicked

                
            if(this.contador == 0)
            {
                        
                this.rp.moverPanelMAV(this);
                this.contador++;
                    
            }else if(this.contador == 1)
            {       
                
                this.rp.moverPanelMAV(this);
                this.rp.moverPanelMEV(this);
                this.contador++;
                        
            }else if(this.contador == 2)
            {
             
                this.rp.moverPanelMEV(this);
                this.rp.moverPanelAPT(this);
                this.contador++;
                
            }else if(this.contador == 3)
            {
                
                this.rp.moverPanelAPT(this);
                this.rp.moverPanelGST(this);
                this.contador++;
                
            }else if(this.contador == 4)
            {
                
                this.rp.moverPanelGST(this);
                this.rp.moverPanelGNS(this);
                this.contador++;
            }
            

    }//GEN-LAST:event_btnSiguienteGraficaMouseClicked

    public Reporte getReporte() {
        return reporte;
    }

    public void setReporte(Reporte reporte) {
        this.reporte = reporte;
    }


    public JDateChooser getJdtFechaFinal() {
        return jdtFechaFinal;
    }

    public void setJdtFechaFinal(JDateChooser jdtFechaFinal) {
        this.jdtFechaFinal = jdtFechaFinal;
    }

    public JDateChooser getJdtFechaInicial() {
        return jdtFechaInicial;
    }

    public void setJdtFechaInicial(JDateChooser jdtFechaInicial) {
        this.jdtFechaInicial = jdtFechaInicial;
    }

    public JPanel getJpnlMAV() {
        return jpnlMAV;
    }

    public void setJpnlMAV(JPanel jpnlMAV) {
        this.jpnlMAV = jpnlMAV;
        
    }

    public JPanel getJpnlMEV() {
        return jpnlMEV;
    }

    public void setJpnlMEV(JPanel jpnlMEV) {
        this.jpnlMEV = jpnlMEV;
    }

    public JPanel getJpnlAPT() {
        return jpnlAPT;
    }

    public void setJpnlAPT(JPanel jpnlAPT) {
        this.jpnlAPT = jpnlAPT;
    }

    public JPanel getJpnlGST() {
        return jpnlGST;
    }

    public void setJpnlGST(JPanel jpnlGST) {
        this.jpnlGST = jpnlGST;
    }

    public JPanel getJpnlGNS() {
        return jpnlGNS;
    }

    public void setJpnlGNS(JPanel jpnlGNS) {
        this.jpnlGNS = jpnlGNS;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnteriorGrafica;
    private javax.swing.JButton btnCancelarGenerar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnSiguienteGrafica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private com.toedter.calendar.JDateChooser jdtFechaFinal;
    private com.toedter.calendar.JDateChooser jdtFechaInicial;
    private javax.swing.JPanel jpnlAPT;
    private javax.swing.JPanel jpnlGNS;
    private javax.swing.JPanel jpnlGST;
    private javax.swing.JPanel jpnlMAV;
    private javax.swing.JPanel jpnlMEV;
    // End of variables declaration//GEN-END:variables
}
