/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.CrearUsuarios;
import Modelo.SQLUsuarios;
import Modelo.Usuario;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class ModuloCrearUsuario extends javax.swing.JPanel{

   private Usuario usuario;
   private CrearUsuarios cus = new CrearUsuarios();



    /** Creates new form InterfazCrearUsuario */
    public ModuloCrearUsuario() {
        initComponents();              
        
     }

   

    
    
    
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        panelEscritura = new javax.swing.JPanel();
        jcmbPrivilegio = new javax.swing.JComboBox<>();
        jtxtContraseñaU = new javax.swing.JTextField();
        jtxtNombreU = new javax.swing.JTextField();
        jcmbEstadoU = new javax.swing.JComboBox<>();
        btnInsertar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jlbInsertar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        jlbEliminar = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblUsuarios = new javax.swing.JTable();
        jrbCantidadU = new javax.swing.JRadioButton();
        jrbNombreU = new javax.swing.JRadioButton();
        jrbPrivilegioU = new javax.swing.JRadioButton();
        jrbEstadoActualU = new javax.swing.JRadioButton();
        jtxtCantidad = new javax.swing.JTextField();
        jtxtNDU = new javax.swing.JTextField();
        jtxtPDU = new javax.swing.JTextField();
        jtxtEAU = new javax.swing.JTextField();
        jrbTodosU = new javax.swing.JRadioButton();
        jtxtIDU = new javax.swing.JTextField();
        btnFiltrarU = new javax.swing.JButton();
        jrbIdUsuario = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEscritura.setBackground(new java.awt.Color(102, 165, 173));
        panelEscritura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jcmbPrivilegio.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcmbPrivilegio.setForeground(new java.awt.Color(102, 102, 102));
        jcmbPrivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "EMPLEADO" }));
        jcmbPrivilegio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEscritura.add(jcmbPrivilegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 140, -1));

        jtxtContraseñaU.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtContraseñaU.setForeground(new java.awt.Color(102, 102, 102));
        jtxtContraseñaU.setText("         CONTRASEÑA DEL USUARIO");
        jtxtContraseñaU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtContraseñaUMouseClicked(evt);
            }
        });
        panelEscritura.add(jtxtContraseñaU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 190, 40));

        jtxtNombreU.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtxtNombreU.setForeground(new java.awt.Color(102, 102, 102));
        jtxtNombreU.setText("           NOMBRE DEL USUARIO ");
        jtxtNombreU.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jtxtNombreU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtxtNombreUMouseClicked(evt);
            }
        });
        jtxtNombreU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreUActionPerformed(evt);
            }
        });
        panelEscritura.add(jtxtNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 190, 40));

        jcmbEstadoU.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jcmbEstadoU.setForeground(new java.awt.Color(153, 153, 153));
        jcmbEstadoU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO", "INACTIVO" }));
        jcmbEstadoU.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelEscritura.add(jcmbEstadoU, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 80, -1));

        btnInsertar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setText("INSERTAR");
        btnInsertar.setBorder(null);
        btnInsertar.setBorderPainted(false);
        btnInsertar.setContentAreaFilled(false);
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsertar.setFocusPainted(false);
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });
        panelEscritura.add(btnInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 90, 40));

        btnModificar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(null);
        btnModificar.setBorderPainted(false);
        btnModificar.setContentAreaFilled(false);
        btnModificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        panelEscritura.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 100, 40));

        jlbInsertar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panelEscritura.add(jlbInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 110, 60));

        btnCancelar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFocusPainted(false);
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panelEscritura.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 90, 40));

        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panelEscritura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 110, 60));

        btnEliminar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("ELIMINAR");
        btnEliminar.setBorder(null);
        btnEliminar.setBorderPainted(false);
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.setFocusPainted(false);
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        panelEscritura.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 90, 40));

        jlbEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panelEscritura.add(jlbEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 110, 60));

        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        panelEscritura.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 110, 60));

        add(panelEscritura, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 250, 590));

        jPanel2.setBackground(new java.awt.Color(63, 50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jtblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID USUARIO", "NOMBRE", "CONTRASEÑA", "ESTADO", "PRIVILEGIOS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblUsuarios);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 0, 528, 440));

        buttonGroup1.add(jrbCantidadU);
        jrbCantidadU.setText("Cantidad");
        jrbCantidadU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbCantidadUMouseClicked(evt);
            }
        });
        add(jrbCantidadU, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 446, -1, -1));

        buttonGroup1.add(jrbNombreU);
        jrbNombreU.setText("Nombre de usuario");
        jrbNombreU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbNombreUMouseClicked(evt);
            }
        });
        add(jrbNombreU, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 482, -1, -1));

        buttonGroup1.add(jrbPrivilegioU);
        jrbPrivilegioU.setText("Privilegio de usuario");
        jrbPrivilegioU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbPrivilegioUMouseClicked(evt);
            }
        });
        add(jrbPrivilegioU, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 516, -1, -1));

        buttonGroup1.add(jrbEstadoActualU);
        jrbEstadoActualU.setText("Estado actual");
        jrbEstadoActualU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbEstadoActualUMouseClicked(evt);
            }
        });
        jrbEstadoActualU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbEstadoActualUActionPerformed(evt);
            }
        });
        add(jrbEstadoActualU, new org.netbeans.lib.awtextra.AbsoluteConstraints(476, 550, 117, -1));

        jtxtCantidad.setEnabled(false);
        add(jtxtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 448, 88, -1));

        jtxtNDU.setEnabled(false);
        add(jtxtNDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 484, 88, -1));

        jtxtPDU.setEnabled(false);
        add(jtxtPDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 518, 88, -1));

        jtxtEAU.setEnabled(false);
        add(jtxtEAU, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 552, 88, -1));

        buttonGroup1.add(jrbTodosU);
        jrbTodosU.setText("traer a todos los usuarios");
        jrbTodosU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbTodosUMouseClicked(evt);
            }
        });
        jrbTodosU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbTodosUActionPerformed(evt);
            }
        });
        add(jrbTodosU, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 480, 180, -1));

        jtxtIDU.setEnabled(false);
        add(jtxtIDU, new org.netbeans.lib.awtextra.AbsoluteConstraints(828, 448, 88, -1));

        btnFiltrarU.setText("Filtrar");
        btnFiltrarU.setEnabled(false);
        btnFiltrarU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFiltrarUMouseClicked(evt);
            }
        });
        add(btnFiltrarU, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 520, 110, 40));

        buttonGroup1.add(jrbIdUsuario);
        jrbIdUsuario.setText("Id usuario");
        jrbIdUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jrbIdUsuarioMouseClicked(evt);
            }
        });
        jrbIdUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbIdUsuarioActionPerformed(evt);
            }
        });
        add(jrbIdUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(734, 446, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtContraseñaUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtContraseñaUMouseClicked
        jtxtContraseñaU.setText("");
    }//GEN-LAST:event_jtxtContraseñaUMouseClicked

    private void jtxtNombreUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtNombreUMouseClicked
        jtxtNombreU.setText("");
    }//GEN-LAST:event_jtxtNombreUMouseClicked

    private void jtxtNombreUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreUActionPerformed

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked

        boolean estadoCampos;    
        usuario = new Usuario();
    
        estadoCampos = cus.obtenerinformación(this);
        
        if(estadoCampos = false)
        {
            
          JOptionPane.showMessageDialog(null, "Inserta Información verídica");
            
        }else
        {
        
        SQLUsuarios.insertarUsuario(usuario);
        
        if(usuario.getIdUsuario() > 0)
        {
            cus.cargarTablaUsuarios(this);
        }

        }
        
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked

        cus.modificarRegistro(this);

    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked

        cus.cancelarEdicionUsuarios(this);

    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
      
        
        
        cus.EliminarRegistroUsuario(this);
        
        
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void jtblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblUsuariosMouseClicked
        
        cus.verificarCamposSeleccionados(this);
                
    }//GEN-LAST:event_jtblUsuariosMouseClicked

    private void jrbEstadoActualUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbEstadoActualUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbEstadoActualUActionPerformed

    private void jrbTodosUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbTodosUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbTodosUActionPerformed

    private void jrbIdUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbIdUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbIdUsuarioActionPerformed

    private void btnFiltrarUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFiltrarUMouseClicked
        

       if(this.jrbTodosU.isSelected())    
       {   
           cus.limpiarTabla(this);
           cus.ConsultarTodosLosUsuarios(this);
           
       }else if(this.jrbCantidadU.isSelected())
       {
           
           cus.limpiarTabla(this);
           cus.consultarCantidadDeUsuarios(this);
           
       }else if(this.jrbEstadoActualU.isSelected())
       {
           
           cus.limpiarTabla(this);
           cus.consultarUsuariosPorEstado(this);
           
       }else if(this.jrbIdUsuario.isSelected())
       {
           
           cus.limpiarTabla(this);
           cus.consultarUsuariosPorId(this);
           
       }else if(this.jrbNombreU.isSelected())
       {
           
           cus.limpiarTabla(this);
           cus.consultarUsuariosPorNombre(this);
           
       }else if(this.jrbPrivilegioU.isSelected())
       {
           
           cus.limpiarTabla(this);
           cus.consultarUsuariosPorPrivilegio(this);
           
       }
            
       

    }//GEN-LAST:event_btnFiltrarUMouseClicked

    private void jrbCantidadUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbCantidadUMouseClicked
        
        usuario = new Usuario();

        this.jtxtEAU.setText("");
        this.jtxtEAU.setEnabled(false);
        this.jtxtIDU.setText("");
        this.jtxtIDU.setEnabled(false);
        this.jtxtNDU.setText("");
        this.jtxtNDU.setEnabled(false);
        this.jtxtPDU.setText("");
        this.jtxtPDU.setEnabled(false);
        this.btnFiltrarU.setEnabled(false);
        cus.activarTxtCantidad(this);        
        
    }//GEN-LAST:event_jrbCantidadUMouseClicked

    private void jrbNombreUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbNombreUMouseClicked

        usuario = new Usuario();
        
        this.jtxtCantidad.setText("");
        this.jtxtCantidad.setEnabled(false);
        this.jtxtEAU.setText("");
        this.jtxtEAU.setEnabled(false);
        this.jtxtIDU.setText("");
        this.jtxtIDU.setEnabled(false);
        this.jtxtPDU.setText("");
        this.jtxtPDU.setEnabled(false);
        this.btnFiltrarU.setEnabled(false);
        cus.activarTxtNDU(this);

    }//GEN-LAST:event_jrbNombreUMouseClicked

    private void jrbPrivilegioUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbPrivilegioUMouseClicked

        usuario = new Usuario();

        this.jtxtCantidad.setText("");
        this.jtxtCantidad.setEnabled(false);
        this.jtxtEAU.setText("");
        this.jtxtEAU.setEnabled(false);
        this.jtxtIDU.setText("");
        this.jtxtIDU.setEnabled(false);
        this.jtxtNDU.setText("");
        this.jtxtNDU.setEnabled(false);
        this.btnFiltrarU.setEnabled(false);    
        cus.activarTxtPDU(this);

    }//GEN-LAST:event_jrbPrivilegioUMouseClicked

    private void jrbEstadoActualUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbEstadoActualUMouseClicked

        usuario = new Usuario();

        this.jtxtCantidad.setText("");
        this.jtxtCantidad.setEnabled(false);
        this.jtxtIDU.setText("");
        this.jtxtIDU.setEnabled(false);
        this.jtxtNDU.setText("");
        this.jtxtNDU.setEnabled(false);
        this.jtxtPDU.setText("");
        this.jtxtPDU.setEnabled(false);
        this.btnFiltrarU.setEnabled(false);
        cus.activarTxtEDU(this);

    }//GEN-LAST:event_jrbEstadoActualUMouseClicked

    private void jrbIdUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbIdUsuarioMouseClicked

        usuario = new Usuario();

        this.jtxtCantidad.setText("");
        this.jtxtCantidad.setEnabled(false);
        this.jtxtEAU.setText("");
        this.jtxtEAU.setEnabled(false);
        this.jtxtNDU.setText("");
        this.jtxtNDU.setEnabled(false);
        this.jtxtPDU.setText("");
        this.jtxtPDU.setEnabled(false);
        this.btnFiltrarU.setEnabled(false);
        cus.activarTxtIDU(this);

    }//GEN-LAST:event_jrbIdUsuarioMouseClicked

    private void jrbTodosUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jrbTodosUMouseClicked

        usuario = new Usuario();
        
        cus.descativarTxt(this);
        
    }//GEN-LAST:event_jrbTodosUMouseClicked

    public Usuario getUsuario() {
        return usuario;
    }

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public CrearUsuarios getCus() {
        return cus;
    }

    public void setCus(CrearUsuarios cus) {
        this.cus = cus;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnEliminar() {
        return btnEliminar;
    }

    public void setBtnEliminar(JButton btnEliminar) {
        this.btnEliminar = btnEliminar;
    }

    public JButton getBtnInsertar() {
        return btnInsertar;
    }

    public void setBtnInsertar(JButton btnInsertar) {
        this.btnInsertar = btnInsertar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public void setBtnModificar(JButton btnModificar) {
        this.btnModificar = btnModificar;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JComboBox<String> getJcmbEstadoU() {
        return jcmbEstadoU;
    }

    public void setJcmbEstadoU(JComboBox<String> jcmbEstadoU) {
        this.jcmbEstadoU = jcmbEstadoU;
    }

    public JComboBox<String> getJcmbPrivilegio() {
        return jcmbPrivilegio;
    }

    public void setJcmbPrivilegio(JComboBox<String> jcmbPrivilegio) {
        this.jcmbPrivilegio = jcmbPrivilegio;
    }

    public JLabel getJlbEliminar() {
        return jlbEliminar;
    }

    public void setJlbEliminar(JLabel jlbEliminar) {
        this.jlbEliminar = jlbEliminar;
    }

    public JLabel getJlbInsertar() {
        return jlbInsertar;
    }

    public void setJlbInsertar(JLabel jlbInsertar) {
        this.jlbInsertar = jlbInsertar;
    }


    public JTable getJtblUsuarios() {
        return jtblUsuarios;
    }

    public void setJtblUsuarios(JTable jtblUsuarios) {
        this.jtblUsuarios = jtblUsuarios;
    }

    public JTextField getJtxtContraseñaU() {
        return jtxtContraseñaU;
    }

    public void setJtxtContraseñaU(JTextField jtxtContraseñaU) {
        this.jtxtContraseñaU = jtxtContraseñaU;
    }

    public JTextField getJtxtNombreU() {
        return jtxtNombreU;
    }

    public void setJtxtNombreU(JTextField jtxtNombreU) {
        this.jtxtNombreU = jtxtNombreU;
    }

    public JPanel getPanelEscritura() {
        return panelEscritura;
    }

    public void setPanelEscritura(JPanel panelEscritura) {
        this.panelEscritura = panelEscritura;
    }

    public JButton getBtnFiltrarU() {
        return btnFiltrarU;
    }

    public void setBtnFiltrarU(JButton btnFiltrarU) {
        this.btnFiltrarU = btnFiltrarU;
    }

    public JRadioButton getJrbCantidadU() {
        return jrbCantidadU;
    }

    public void setJrbCantidadU(JRadioButton jrbCantidadU) {
        this.jrbCantidadU = jrbCantidadU;
    }

    public JRadioButton getJrbEstadoActualU() {
        return jrbEstadoActualU;
    }

    public void setJrbEstadoActualU(JRadioButton jrbEstadoActualU) {
        this.jrbEstadoActualU = jrbEstadoActualU;
    }

    public JRadioButton getJrbIdUsuario() {
        return jrbIdUsuario;
    }

    public void setJrbIdUsuario(JRadioButton jrbIdUsuario) {
        this.jrbIdUsuario = jrbIdUsuario;
    }

    public JRadioButton getJrbNombreU() {
        return jrbNombreU;
    }

    public void setJrbNombreU(JRadioButton jrbNombreU) {
        this.jrbNombreU = jrbNombreU;
    }

    public JRadioButton getJrbPrivilegioU() {
        return jrbPrivilegioU;
    }

    public void setJrbPrivilegioU(JRadioButton jrbPrivilegioU) {
        this.jrbPrivilegioU = jrbPrivilegioU;
    }

    public JRadioButton getJrbTodosU() {
        return jrbTodosU;
    }

    public void setJrbTodosU(JRadioButton jrbTodosU) {
        this.jrbTodosU = jrbTodosU;
    }

    public JTextField getJtxtCantidad() {
        return jtxtCantidad;
    }

    public void setJtxtCantidad(JTextField jtxtCantidad) {
        this.jtxtCantidad = jtxtCantidad;
    }

    public JTextField getJtxtEAU() {
        return jtxtEAU;
    }

    public void setJtxtEAU(JTextField jtxtEAU) {
        this.jtxtEAU = jtxtEAU;
    }

    public JTextField getJtxtIDU() {
        return jtxtIDU;
    }

    public void setJtxtIDU(JTextField jtxtIDU) {
        this.jtxtIDU = jtxtIDU;
    }

    public JTextField getJtxtNDU() {
        return jtxtNDU;
    }

    public void setJtxtNDU(JTextField jtxtNDU) {
        this.jtxtNDU = jtxtNDU;
    }

    public JTextField getJtxtPDU() {
        return jtxtPDU;
    }

    public void setJtxtPDU(JTextField jtxtPDU) {
        this.jtxtPDU = jtxtPDU;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    

 

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrarU;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcmbEstadoU;
    private javax.swing.JComboBox<String> jcmbPrivilegio;
    private javax.swing.JLabel jlbEliminar;
    private javax.swing.JLabel jlbInsertar;
    private javax.swing.JRadioButton jrbCantidadU;
    private javax.swing.JRadioButton jrbEstadoActualU;
    private javax.swing.JRadioButton jrbIdUsuario;
    private javax.swing.JRadioButton jrbNombreU;
    private javax.swing.JRadioButton jrbPrivilegioU;
    private javax.swing.JRadioButton jrbTodosU;
    private javax.swing.JTable jtblUsuarios;
    private javax.swing.JTextField jtxtCantidad;
    private javax.swing.JTextField jtxtContraseñaU;
    private javax.swing.JTextField jtxtEAU;
    private javax.swing.JTextField jtxtIDU;
    private javax.swing.JTextField jtxtNDU;
    private javax.swing.JTextField jtxtNombreU;
    private javax.swing.JTextField jtxtPDU;
    private javax.swing.JPanel panelEscritura;
    // End of variables declaration//GEN-END:variables

}
